import {test,expect} from '@playwright/test';
import {readFile} from 'node:fs/promises';
import {inspectStoredZip} from '../../src/application/portable-zip.js';
import {readStoredDayPackage} from '../../src/application/journey-package-restore.js';

const photo=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=','base64');
const feature=(id,name,type,sequence)=>({id,name,type,day:9,sequence,status:'planned',photoRequirement:'required',visible:true,geometry:{kind:'point',coordinates:[{lat:30+sequence/100,lon:-90}]}});
const payload={format:'CannonMap Project',settings:{dayFilter:'all'},project:{projectId:'field-export-day-nine',name:'Field Export Day 9',features:[feature('cp','9.1 Checkpoint','checkpoint',1),feature('hotel','9.2 Hotel','hotel',2)],competitors:[]}};

async function load(page){await page.goto('/?e2e=field-export-day-nine');await page.waitForFunction(()=>document.documentElement.dataset.cannonmapReady==='true');await page.locator('#projectInput').setInputFiles({name:'field.cmap',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))});}
async function capture(page,name){await page.evaluate(()=>window.CannonMapTest.completeCurrentCheckpoint(false));await page.locator('#rallyCameraInput').setInputFiles({name,mimeType:'image/png',buffer:photo});}

test('finalized Day 9 exports verified photos, Journal, restorable backup, and Journey manifest while filter is all',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='iPhone 13 portrait');await load(page);await capture(page,'checkpoint.png');await expect(page.locator('#rallyNextName')).toContainText('Hotel');await capture(page,'hotel.png');await expect(page.locator('#rallyDayComplete')).toBeVisible();
  const before=await page.evaluate(async()=>({media:await window.CannonMapTest.missionMediaRecords(),events:await window.CannonMapTest.missionControlJournalEvents()}));expect(before.media).toHaveLength(8);expect(before.media.filter(item=>item.name.includes('_Hotel')).every(item=>item.metadata.objectiveType==='hotel')).toBeTruthy();expect(before.events.some(event=>event.eventType==='checkpoint_arrival')).toBeTruthy();expect(before.events.some(event=>event.eventType==='photo_added'&&event.metadata.objectiveType==='hotel')).toBeTruthy();expect(before.events.some(event=>event.eventType==='hotel_arrival')).toBeTruthy();expect(before.events.some(event=>event.eventType==='day_finished')).toBeTruthy();
  for(let index=0;index<3;index++)await page.evaluate(()=>window.CannonMapTest.evaluateCheckpointArrival(10));const failures=await page.evaluate(()=>window.CannonMapTest.rallyDebugEntries().filter(entry=>entry.type==='objective_selection_failed'&&entry.reason==='day-complete'));expect(failures).toHaveLength(0);
  await page.locator('#rallyBackupToday').click();let pending=page.waitForEvent('download');await page.locator('#rallyBackupDayPhotos').click();const photos=await pending,photoBytes=await readFile(await photos.path()),entries=await inspectStoredZip(new Blob([photoBytes]));expect(photos.suggestedFilename()).toBe('Day09_Photos.zip');expect(entries).toHaveLength(8);expect(entries.every(entry=>entry.size>0)).toBeTruthy();expect(entries.filter(entry=>entry.name.startsWith('Hotels/'))).toHaveLength(4);
  pending=page.waitForEvent('download');await page.locator('#rallyBackupDayJournal').click();const journal=await pending,journalEvents=JSON.parse(await readFile(await journal.path(),'utf8'));expect(journal.suggestedFilename()).toBe('Day09_Journal.json');expect(journalEvents.length).toBeGreaterThan(4);expect(journalEvents.some(event=>event.eventType==='checkpoint_arrival')).toBeTruthy();expect(journalEvents.some(event=>event.eventType==='photo_added')).toBeTruthy();expect(journalEvents.some(event=>event.eventType==='hotel_arrival')).toBeTruthy();expect(journalEvents.some(event=>event.eventType==='day_finished')).toBeTruthy();
  pending=page.waitForEvent('download');await page.locator('#rallyBackupDayPackage').click();const backup=await pending,backupBytes=await readFile(await backup.path()),restorable=await readStoredDayPackage(new Blob([backupBytes]));expect(backup.suggestedFilename()).toBe('Day09_Backup.cmapday.zip');expect(restorable.manifest.mediaCount).toBe(8);expect(restorable.journal.length).toBeGreaterThan(4);expect(restorable.media.filter(item=>item.metadata.objectiveType==='hotel')).toHaveLength(4);const stages=await page.evaluate(()=>window.CannonMapTest.rallyDebugEntries().map(entry=>entry.type).filter(type=>type.startsWith('backup_')));expect(stages).toEqual(expect.arrayContaining(['backup_started','backup_project_resolved','backup_day_resolved','backup_journal_loaded','backup_media_loaded','backup_manifest_created','backup_zip_created','backup_verified','backup_download_requested','backup_completed']));
  await page.locator('#rallyBackupClose').click();await page.locator('#rallyMoreButton').click();await page.locator('#rallyPhotoViewerButton').click();pending=page.waitForEvent('download');await page.locator('#rallyExportJourneyPhotos').click();const manifestDownload=await pending,journeyManifest=JSON.parse(await readFile(await manifestDownload.path(),'utf8'));expect(journeyManifest.projects).toHaveLength(1);expect(journeyManifest.projects[0]).toMatchObject({projectId:'field-export-day-nine',projectName:'Field Export Day 9',originalPhotoCount:4,evidencePhotoCount:4,dayCount:1,completedState:true});
});
