import {test,expect} from '@playwright/test';
import {createPhotoExportService} from '../../src/application/photo-export-service.js';

const point=(id,name,status,{type='checkpoint',scoreAwarded=0,pairId=null}={})=>({id,name,type,day:9,status,points:scoreAwarded,scoreAwarded,photoPairId:pairId,geometry:{kind:'point',coordinates:[{lat:30,lon:-90}]}});
const project={projectId:'restore-review-project',id:'restore-review-project',name:'America 250 – 2026',features:[point('cp91','9.1 Restored Checkpoint','collected',{scoreAwarded:10,pairId:'pair-1'}),point('cp92','9.2 Restored Checkpoint','collected',{scoreAwarded:10,pairId:'pair-2'}),...Array.from({length:5},(_,index)=>point(`cp9${index+3}`,`9.${index+3} Deferred Checkpoint`,'deferred')),point('cp98','9.8 Failed Checkpoint','failed'),point('hotel9','9.9 Hotel','collected',{type:'hotel',pairId:'pair-3'}),{id:'cp31',name:'31.1 Future Checkpoint',type:'checkpoint',day:31,status:'upcoming',points:10,geometry:{kind:'point',coordinates:[{lat:31,lon:-91}]}}],rallyExecution:{days:{9:{dayNumber:9,status:'complete',score:20,totalCollected:3,totalDeferred:5},31:{dayNumber:31,status:'ready'}}},competitors:[]};
const journal=Array.from({length:16},(_,index)=>({eventId:`event-${index}`,projectId:project.projectId,eventType:index===15?'day_finished':index%4===0?'checkpoint_arrival':index%4===1?'photo_pair_completed':index%4===2?'checkpoint_completed':'checkpoint_deferred',metadata:{dayNumber:9},references:index%4===1?{pairId:`pair-${(index%3)+1}`}:{}}));
let packageBytes,incompletePackageBytes;
test.beforeAll(async()=>{const roles=[['front','original'],['front','evidence'],['rear','original'],['rear','evidence']],records=[1,2,3].flatMap(pair=>roles.map(([cameraRole,role],index)=>({mediaId:`media-${pair}-${index}`,projectId:project.projectId,checkpointId:pair===3?'hotel9':`cp9${pair}`,objectiveType:pair===3?'hotel':'checkpoint',journalEventId:`event-${pair}`,pairId:`pair-${pair}`,pairStatus:'complete',cameraRole,role,name:`Day09_Pair${pair}_${cameraRole}_${role}.jpg`,mimeType:'image/jpeg',metadata:{dayNumber:9,pairId:`pair-${pair}`,cameraRole,objectiveType:pair===3?'hotel':'checkpoint'},blob:new Blob([`bytes-${pair}-${cameraRole}-${role}`],{type:'image/jpeg'})}))),service=createPhotoExportService({repository:{listProjectPhotos:async()=>records}}),file=await service.dayBackup(project.projectId,9,{project,journal,settings:{dayFilter:'all',rallyDays:{9:{status:'complete',score:20},31:{status:'ready'}}},applicationVersion:'test',buildId:'restore-review'});packageBytes=Buffer.from(await file.blob.arrayBuffer());const incomplete={...structuredClone(project),projectId:'interrupted-day-project',id:'interrupted-day-project',name:'Interrupted Rally'};incomplete.rallyExecution.days[9].status='active';incomplete.features.find(item=>item.id==='cp98').status='active';const interruptedMedia=records.map(item=>({...item,projectId:incomplete.projectId})),interruptedJournal=journal.map(item=>({...item,projectId:incomplete.projectId})),interruptedService=createPhotoExportService({repository:{listProjectPhotos:async()=>interruptedMedia}}),interruptedFile=await interruptedService.dayBackup(incomplete.projectId,9,{project:incomplete,journal:interruptedJournal,settings:{dayFilter:'9',rallyDays:{9:{status:'active',score:20}}},applicationVersion:'test',buildId:'restore-review'});incompletePackageBytes=Buffer.from(await interruptedFile.blob.arrayBuffer());});
const input=()=>({name:'Day09_Backup.cmapday.zip',mimeType:'application/zip',buffer:packageBytes});
async function loadOriginal(page,id){await page.goto(`/?e2e=${id}`);await page.waitForFunction(()=>document.documentElement.dataset.cannonmapReady==='true');await page.locator('#projectInput').setInputFiles({name:'original.cmap',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'CannonMap Project',settings:{dayFilter:'all'},project}))});}
const isIPhone=testInfo=>['iPhone 13 portrait','iPhone 13 landscape'].includes(testInfo.project.name);

test('CANCEL changes no Project, Journal, or media records',async({page},testInfo)=>{test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-cancel');page.on('dialog',dialog=>dialog.dismiss());const before=await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).length,journal:(await window.CannonMapTest.missionControlJournalEvents()).length}));await page.locator('#rallyDayRestore').setInputFiles(input());await page.waitForTimeout(300);expect(await page.locator('#restoreResultDialog').isVisible()).toBeFalsy();expect(await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).length,journal:(await window.CannonMapTest.missionControlJournalEvents()).length}))).toEqual(before);});

test('completed COPY verifies and preserves the active Mission Control project until explicit switch',async({page},testInfo)=>{
  test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-copy');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();
  await expect(page.locator('#restoreResultTitle')).toHaveText('DAY BACKUP VERIFIED / RESTORED');await expect(page.locator('#restoreResultCopy')).toContainText('RECOVERY COPY');await expect(page.locator('#restoreResultSummary')).toContainText('America 250 – 2026 Recovery Copy');await expect(page.locator('#restoreResultSummary')).toContainText('Journal event count');await expect(page.locator('#restoreResultSummary')).toContainText('16');await expect(page.locator('#restoreResultSummary')).toContainText('Media count');await expect(page.locator('#restoreResultSummary')).toContainText('12');await expect(page.locator('#restoreResultSummary')).toContainText('Verified');await expect(page.locator('#restoreResultSummary')).toContainText('20');await expect(page.locator('#rallyActiveProjectName')).toHaveText('America 250 – 2026');await expect(page.locator('#rallyReviewNotice')).toBeHidden();
  await page.locator('#restoreViewJournal').click();await expect(page.locator('#restoreJournalDialog')).toBeVisible();await expect(page.locator('#restoreJournalContent')).toContainText('day_finished');await page.locator('#restoreJournalClose').click();await page.locator('#restoreSwitchProject').click();await expect(page.locator('#rallyReviewNotice')).toBeVisible();await expect(page.locator('#rallyDayCompleteTitle')).toHaveText('✓ Day Complete');await expect(page.locator('#rallyStartNextDay')).toBeHidden();await expect(page.locator('#rallyActiveProjectName')).toContainText('Recovery Copy');
  const before=await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).map(item=>item.mediaId),journal:(await window.CannonMapTest.missionControlJournalEvents()).map(item=>item.eventId)}));expect(before.media).toHaveLength(12);expect(before.journal).toHaveLength(16);await page.evaluate(()=>{window.CannonMapTest.evaluateCheckpointArrival(10);return window.CannonMapTest.completeCurrentCheckpoint(false);});expect(await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).map(item=>item.mediaId),journal:(await window.CannonMapTest.missionControlJournalEvents()).map(item=>item.eventId)}))).toEqual(before);
  const events=await page.evaluate(()=>window.CannonMapTest.rallyDebugEntries().map(item=>item.type));for(const name of ['restore_copy_started','restore_package_identity','restore_copy_identity_created','restore_project_written','restore_day_written','restore_journal_written','restore_media_written','restore_postwrite_verification_started','restore_postwrite_verification_passed','restore_summary_presented','restore_copy_completed'])expect(events).toContain(name);
});

test('completed COPY survives reload without activating or duplicating the recovery project',async({page},testInfo)=>{test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-copy-reload');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();await page.locator('#restoreResultClose').click();await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.cannonmapReady==='true');await expect(page.locator('#rallyActiveProjectName')).toHaveText('America 250 – 2026');await expect(page.locator('#rallyReviewNotice')).toBeHidden();await page.locator('#rallyMoreButton').click();await expect.poll(()=>page.locator('#rallyProjectSelect option').count()).toBeGreaterThan(1);const names=await page.locator('#rallyProjectSelect option').allTextContents();expect(names.filter(name=>name.includes('Recovery Copy'))).toHaveLength(1);});

test('View Photos opens restored Capture Pair media',async({page},testInfo)=>{test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-photos');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();await page.locator('#restoreViewPhotos').click();await expect(page.locator('#rallyPhotoViewer')).toBeVisible();await expect(page.locator('#rallyPhotoGallery')).toContainText('Original: Available');await expect(page.locator('#rallyPhotoGallery')).toContainText('Evidence: Available');});

test('incomplete backup offers explicit resume and switches only after authorization',async({page},testInfo)=>{test.skip(testInfo.project.name!=='iPhone 13 portrait');await loadOriginal(page,'restore-incomplete');page.on('dialog',dialog=>dialog.accept());await page.locator('#rallyDayRestore').setInputFiles({name:'Interrupted_Day09.cmapday.zip',mimeType:'application/zip',buffer:incompletePackageBytes});await expect(page.locator('#restoreResultDialog')).toBeVisible();await expect(page.locator('#restoreViewDay')).toHaveText('RESUME RESTORED DAY');await expect(page.locator('#rallyActiveProjectName')).toHaveText('America 250 – 2026');await page.locator('#restoreViewDay').click();await expect(page.locator('#rallyActiveProjectName')).toHaveText('Interrupted Rally');await expect(page.locator('#rallyObjectiveStatus')).toContainText('active');});

test('Checkpoint Photos stays in More grid flow and project identity refreshes immediately',async({page},testInfo)=>{test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-layout-header');await page.locator('#rallyMoreButton').click();const photos=page.locator('#rallyPhotoViewerButton'),storage=page.locator('.rally-storage-diagnostics');await expect(photos).toBeVisible();const layout=await photos.evaluate((node,storageNode)=>{const a=node.getBoundingClientRect(),b=storageNode.getBoundingClientRect(),style=getComputedStyle(node);return {position:style.position,overlap:!(a.bottom<=b.top||a.top>=b.bottom||a.right<=b.left||a.left>=b.right)};},await storage.elementHandle());expect(layout).toEqual({position:'static',overlap:false});await page.locator('#projectName').evaluate(node=>{node.value='Renamed Rally';node.dispatchEvent(new Event('change',{bubbles:true}));});await expect(page.locator('#rallyActiveProjectName')).toHaveText('Renamed Rally');await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.cannonmapReady==='true');await expect(page.locator('#rallyActiveProjectName')).toHaveText('Renamed Rally');});
