import {test,expect} from '@playwright/test';
import {createPhotoExportService} from '../../src/application/photo-export-service.js';

const point=(id,name,status,{type='checkpoint',scoreAwarded=0,pairId=null}={})=>({id,name,type,day:9,status,points:scoreAwarded,scoreAwarded,photoPairId:pairId,geometry:{kind:'point',coordinates:[{lat:30,lon:-90}]}});
const project={projectId:'restore-review-project',id:'restore-review-project',name:'America 250 – 2026',features:[point('cp91','9.1 Restored Checkpoint','collected',{scoreAwarded:10,pairId:'pair-1'}),point('cp92','9.2 Restored Checkpoint','collected',{scoreAwarded:10,pairId:'pair-2'}),...Array.from({length:5},(_,index)=>point(`cp9${index+3}`,`9.${index+3} Deferred Checkpoint`,'deferred')),point('cp98','9.8 Failed Checkpoint','failed'),point('hotel9','9.9 Hotel','collected',{type:'hotel',pairId:'pair-3'}),{id:'cp31',name:'31.1 Future Checkpoint',type:'checkpoint',day:31,status:'upcoming',points:10,geometry:{kind:'point',coordinates:[{lat:31,lon:-91}]}}],rallyExecution:{days:{9:{dayNumber:9,status:'complete',score:20,totalCollected:3,totalDeferred:5},31:{dayNumber:31,status:'ready'}}},competitors:[]};
const journal=Array.from({length:16},(_,index)=>({eventId:`event-${index}`,projectId:project.projectId,eventType:index===15?'day_finished':index%4===0?'checkpoint_arrival':index%4===1?'photo_pair_completed':index%4===2?'checkpoint_completed':'checkpoint_deferred',metadata:{dayNumber:9},references:index%4===1?{pairId:`pair-${(index%3)+1}`}:{}}));
let packageBytes;
test.beforeAll(async()=>{const roles=[['front','original'],['front','evidence'],['rear','original'],['rear','evidence']],records=[1,2,3].flatMap(pair=>roles.map(([cameraRole,role],index)=>({mediaId:`media-${pair}-${index}`,projectId:project.projectId,checkpointId:pair===3?'hotel9':`cp9${pair}`,objectiveType:pair===3?'hotel':'checkpoint',journalEventId:`event-${pair}`,pairId:`pair-${pair}`,pairStatus:'complete',cameraRole,role,name:`Day09_Pair${pair}_${cameraRole}_${role}.jpg`,mimeType:'image/jpeg',metadata:{dayNumber:9,pairId:`pair-${pair}`,cameraRole,objectiveType:pair===3?'hotel':'checkpoint'},blob:new Blob([`bytes-${pair}-${cameraRole}-${role}`],{type:'image/jpeg'})}))),service=createPhotoExportService({repository:{listProjectPhotos:async()=>records}}),file=await service.dayBackup(project.projectId,9,{project,journal,settings:{dayFilter:'all',rallyDays:{9:{status:'complete',score:20},31:{status:'ready'}}},applicationVersion:'test',buildId:'restore-review'});packageBytes=Buffer.from(await file.blob.arrayBuffer());});
const input=()=>({name:'Day09_Backup.cmapday.zip',mimeType:'application/zip',buffer:packageBytes});
async function loadOriginal(page,id){await page.goto(`/?e2e=${id}`);await page.waitForFunction(()=>document.documentElement.dataset.cannonmapReady==='true');await page.locator('#projectInput').setInputFiles({name:'original.cmap',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'CannonMap Project',settings:{dayFilter:'all'},project}))});}
const isIPhone=testInfo=>['iPhone 13 portrait','iPhone 13 landscape'].includes(testInfo.project.name);

test('CANCEL changes no Project, Journal, or media records',async({page},testInfo)=>{test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-cancel');page.on('dialog',dialog=>dialog.dismiss());const before=await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).length,journal:(await window.CannonMapTest.missionControlJournalEvents()).length}));await page.locator('#rallyDayRestore').setInputFiles(input());await page.waitForTimeout(300);expect(await page.locator('#restoreResultDialog').isVisible()).toBeFalsy();expect(await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).length,journal:(await window.CannonMapTest.missionControlJournalEvents()).length}))).toEqual(before);});

test('COPY shows verified summary and opens immutable completed-day review without losing Day 31',async({page},testInfo)=>{
  test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-copy');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();
  await expect(page.locator('#restoreResultTitle')).toHaveText('DAY 9 RESTORED');await expect(page.locator('#restoreResultCopy')).toContainText('RECOVERY COPY');await expect(page.locator('#restoreResultSummary')).toContainText('America 250 – 2026 Recovery Copy');await expect(page.locator('#restoreResultSummary')).toContainText('16 events');await expect(page.locator('#restoreResultSummary')).toContainText('12 files');await expect(page.locator('#restoreResultSummary')).toContainText('Verified');await expect(page.locator('#restoreResultSummary')).toContainText('20');await expect(page.locator('#rallyNextName')).not.toHaveText('No objectives available');await expect(page.locator('#rallyReviewNotice')).toBeVisible();
  await page.locator('#restoreViewJournal').click();await expect(page.locator('#restoreJournalDialog')).toBeVisible();await expect(page.locator('#restoreJournalContent')).toContainText('day_finished');await page.locator('#restoreJournalClose').click();await page.locator('#restoreViewDay').scrollIntoViewIfNeeded();await page.locator('#restoreViewDay').click();await expect(page.locator('#rallyReviewNotice')).toBeVisible();await expect(page.locator('#rallyDayCompleteTitle')).toHaveText('✓ Day Complete');await expect(page.locator('#rallyStartNextDay')).toBeHidden();
  const before=await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).map(item=>item.mediaId),journal:(await window.CannonMapTest.missionControlJournalEvents()).map(item=>item.eventId)}));expect(before.media).toHaveLength(12);expect(before.journal).toHaveLength(16);await page.evaluate(()=>{window.CannonMapTest.evaluateCheckpointArrival(10);return window.CannonMapTest.completeCurrentCheckpoint(false);});expect(await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).map(item=>item.mediaId),journal:(await window.CannonMapTest.missionControlJournalEvents()).map(item=>item.eventId)}))).toEqual(before);
  const events=await page.evaluate(()=>window.CannonMapTest.rallyDebugEntries().map(item=>item.type));for(const name of ['restore_copy_started','restore_package_identity','restore_copy_identity_created','restore_project_written','restore_day_written','restore_journal_written','restore_media_written','restore_postwrite_verification_started','restore_postwrite_verification_passed','restore_active_project_switch_started','restore_active_project_switch_completed','restore_review_day_selected','restore_summary_presented','restore_copy_completed'])expect(events).toContain(name);
});

test('COPY survives an installed-PWA-equivalent reload without duplicating the recovery project',async({page},testInfo)=>{test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-copy-reload');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();await page.locator('#restoreResultClose').click();await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.cannonmapReady==='true');await expect(page.locator('#rallyReviewNotice')).toBeVisible();await expect(page.locator('#rallyDayCompleteTitle')).toHaveText('✓ Day Complete');await expect(page.locator('#rallyNextName')).not.toHaveText('No objectives available');await expect(page.locator('#rallyActiveProjectName')).toContainText('Recovery Copy');const restored=await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).length,journal:(await window.CannonMapTest.missionControlJournalEvents()).length}));expect(restored).toEqual({media:12,journal:16});await page.locator('#rallyMoreButton').click();await expect.poll(()=>page.locator('#rallyProjectSelect option').count()).toBeGreaterThan(1);const names=await page.locator('#rallyProjectSelect option').allTextContents();expect(names.filter(name=>name.includes('Recovery Copy'))).toHaveLength(1);});

test('View Photos opens restored Capture Pair media',async({page},testInfo)=>{test.skip(!isIPhone(testInfo));await loadOriginal(page,'restore-photos');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();await page.locator('#restoreViewPhotos').click();await expect(page.locator('#rallyPhotoViewer')).toBeVisible();await expect(page.locator('#rallyPhotoGallery')).toContainText('Original: Available');await expect(page.locator('#rallyPhotoGallery')).toContainText('Evidence: Available');});
