import {test,expect} from '@playwright/test';
import {createPhotoExportService} from '../../src/application/photo-export-service.js';

const project={projectId:'restore-review-project',id:'restore-review-project',name:'America 250 – 2026',features:[{id:'cp9',name:'9.1 Restored Checkpoint',type:'checkpoint',day:9,status:'collected',points:20,scoreAwarded:20,photoPairId:'pair-9',geometry:{kind:'point',coordinates:[{lat:30,lon:-90}]}},{id:'hotel9',name:'9.2 Hotel',type:'hotel',day:9,status:'collected',points:0,scoreAwarded:0,geometry:{kind:'point',coordinates:[{lat:30.1,lon:-90}]}},{id:'cp31',name:'31.1 Future Checkpoint',type:'checkpoint',day:31,status:'upcoming',points:10,geometry:{kind:'point',coordinates:[{lat:31,lon:-91}]}}],rallyExecution:{days:{9:{dayNumber:9,status:'complete',score:20,totalCollected:2,totalDeferred:0},31:{dayNumber:31,status:'ready'}}},competitors:[]};
const journal=[{eventId:'arrival',projectId:project.projectId,eventType:'checkpoint_arrival',metadata:{dayNumber:9}},{eventId:'photo',projectId:project.projectId,eventType:'photo_added',metadata:{dayNumber:9},references:{pairId:'pair-9'}},{eventId:'finished',projectId:project.projectId,eventType:'day_finished',metadata:{dayNumber:9}}];
let packageBytes;
test.beforeAll(async()=>{const roles=[['front','original'],['front','evidence'],['rear','original'],['rear','evidence']],records=roles.map(([cameraRole,role],index)=>({mediaId:`media-${index}`,projectId:project.projectId,checkpointId:'cp9',journalEventId:'photo',pairId:'pair-9',pairStatus:'complete',cameraRole,role,name:`Day09_${cameraRole}_${role}.jpg`,mimeType:'image/jpeg',metadata:{dayNumber:9,pairId:'pair-9',cameraRole},blob:new Blob([`bytes-${cameraRole}-${role}`],{type:'image/jpeg'})})),service=createPhotoExportService({repository:{listProjectPhotos:async()=>records}}),file=await service.dayBackup(project.projectId,9,{project,journal,settings:{dayFilter:'all',rallyDays:{9:{status:'complete',score:20},31:{status:'ready'}}},applicationVersion:'test',buildId:'restore-review'});packageBytes=Buffer.from(await file.blob.arrayBuffer());});
const input=()=>({name:'Day09_Backup.cmapday.zip',mimeType:'application/zip',buffer:packageBytes});
async function loadOriginal(page,id){await page.goto(`/?e2e=${id}`);await page.waitForFunction(()=>document.documentElement.dataset.cannonmapReady==='true');await page.locator('#projectInput').setInputFiles({name:'original.cmap',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'CannonMap Project',settings:{dayFilter:'all'},project}))});}

test('CANCEL changes no Project, Journal, or media records',async({page},testInfo)=>{test.skip(testInfo.project.name!=='iPhone 13 portrait');await loadOriginal(page,'restore-cancel');page.on('dialog',dialog=>dialog.dismiss());const before=await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).length,journal:(await window.CannonMapTest.missionControlJournalEvents()).length}));await page.locator('#rallyDayRestore').setInputFiles(input());await page.waitForTimeout(300);expect(await page.locator('#restoreResultDialog').isVisible()).toBeFalsy();expect(await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).length,journal:(await window.CannonMapTest.missionControlJournalEvents()).length}))).toEqual(before);});

test('COPY shows verified summary and opens immutable completed-day review without losing Day 31',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='iPhone 13 portrait');await loadOriginal(page,'restore-copy');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();
  await expect(page.locator('#restoreResultTitle')).toHaveText('DAY 9 RESTORED');await expect(page.locator('#restoreResultCopy')).toContainText('RECOVERY COPY');await expect(page.locator('#restoreResultSummary')).toContainText('America 250 – 2026 Recovery Copy');await expect(page.locator('#restoreResultSummary')).toContainText('3 events');await expect(page.locator('#restoreResultSummary')).toContainText('4 files');await expect(page.locator('#restoreResultSummary')).toContainText('Verified');
  await page.locator('#restoreViewJournal').click();await expect(page.locator('#restoreJournalDialog')).toBeVisible();await expect(page.locator('#restoreJournalContent')).toContainText('day_finished');await page.locator('#restoreJournalClose').click();await page.locator('#restoreViewDay').scrollIntoViewIfNeeded();await page.locator('#restoreViewDay').click();await expect(page.locator('#rallyReviewNotice')).toBeVisible();await expect(page.locator('#rallyDayCompleteTitle')).toHaveText('✓ Day Complete');await expect(page.locator('#rallyStartNextDay')).toBeHidden();
  const before=await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).map(item=>item.mediaId),journal:(await window.CannonMapTest.missionControlJournalEvents()).map(item=>item.eventId)}));await page.evaluate(()=>{window.CannonMapTest.evaluateCheckpointArrival(10);return window.CannonMapTest.completeCurrentCheckpoint(false);});expect(await page.evaluate(async()=>({media:(await window.CannonMapTest.missionMediaRecords()).map(item=>item.mediaId),journal:(await window.CannonMapTest.missionControlJournalEvents()).map(item=>item.eventId)}))).toEqual(before);
});

test('View Photos opens restored Capture Pair media',async({page},testInfo)=>{test.skip(testInfo.project.name!=='iPhone 13 portrait');await loadOriginal(page,'restore-photos');page.on('dialog',dialog=>dialog.type()==='confirm'?dialog.accept():dialog.accept('COPY'));await page.locator('#rallyDayRestore').setInputFiles(input());await expect(page.locator('#restoreResultDialog')).toBeVisible();await page.locator('#restoreViewPhotos').click();await expect(page.locator('#rallyPhotoViewer')).toBeVisible();await expect(page.locator('#rallyPhotoGallery')).toContainText('Original: Available');await expect(page.locator('#rallyPhotoGallery')).toContainText('Evidence: Available');});
