import {createCoreCompatibility} from './src/core/compatibility.js';
import * as geometry from './src/domain/geo/geometry.js';
import {createMapEngine} from './src/ui/map/map-engine.js';
import {createProjectWorkflows} from './src/application/project-workflows.js';
import * as checkpoints from './src/domain/checkpoints/workflow.js';
import {renderRally as presentRally} from './src/ui/rally/presenter.js';
import {wireRallyController} from './src/ui/rally/controller.js';
import {wireProjectController} from './src/ui/project/controller.js';
import {createFeatureFlags} from './src/core/feature-flags.js';
import {createObservationCapture,OBSERVATION_CAPTURE_FEATURE_FLAG} from './src/application/observation-capture.js';
import {createSecureObservationUploader,SECURE_INGESTION_FEATURE_FLAG} from './src/application/secure-observation-upload.js';
import {createRallyAnalyticsService,RALLY_ANALYTICS_FEATURE_FLAG} from './src/application/rally-analytics-service.js';
import {createAnalyticsRepository,createObservationCaptureRepository,createJournalRepository,createMediaRepository,openIndexedDbV2,V2_FEATURE_FLAG} from './src/infrastructure/indexeddb/index.js';
import {createFirebaseAuthentication} from './src/infrastructure/firebase/authentication.js';
import {createObservationIngressClient} from './src/infrastructure/firebase/observation-ingress-client.js';
import {createRallyJournalService} from './src/application/rally-journal-service.js';
import {createCheckpointPhotoService,CHECKPOINT_PHOTO_FEATURE_FLAG} from './src/application/checkpoint-photo-service.js';
import {captureSequentialPair,isCameraCaptureSupported} from './src/application/camera-capture.js';

const APP_VERSION = '0.7.1';
const BUILD_ID = '2026.07.27.m11g';
