'use strict';

/* Desktop route-builder extension. The phone Rally Mode intentionally remains unchanged. */
const PLANNER_ALTERNATIVES=new Set(['Primary','Paved','Dirt','Weather','Fuel bailout','Hotel bailout']);
const ROUTING_PROVIDERS={'osrm-demo':{label:'OSRM public demo',profiles:['driving'],requiresInternet:true,async calculate(points,profile='driving'){if(profile!=='driving')throw new Error('The OSRM public demo supports the driving profile only.');if(!navigator.onLine)throw new Error('CannonMap is offline. Use a manual track or provisional connection.');const coordinates=points.map(point=>`${point.lon},${point.lat}`).join(';'),url=`https://router.project-osrm.org/route/v1/${profile}/${coordinates}?overview=full&geometries=geojson&steps=false`,response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`OSRM returned HTTP ${response.status}.`);const payload=await response.json(),route=payload.routes?.[0];if(payload.code!=='Ok'||!route?.geometry?.coordinates?.length)throw new Error(payload.message||'OSRM could not calculate this route.');return {coordinates:route.geometry.coordinates.map(([lon,lat])=>({lat,lon})),distanceMiles:Number(route.distance||0)/1609.344,durationMinutes:Number(route.duration||0)/60,provider:'OSRM public demo',profile};}}};
const plannerPoint=f=>f?.geometry?.kind==='point'?f.geometry.coordinates[0]:null;
const activePlannerDay=()=>{const day=Number(state.settings.dayFilter);return day>=1&&day<=8?day:0;};
const dayFeatures=day=>state.project.features.filter(f=>Number(f.day)===Number(day));
const isDayStart=f=>f?.plannerRole==='start'||(f?.geometry?.kind==='point'&&/\b(day\s*[1-8]\s*)?start\b/i.test(f.name||''));
const isDayFinish=f=>f?.plannerRole==='finish'||f?.type==='hotel'||(f?.geometry?.kind==='point'&&/\b(hotel|finish|overnight|lodging)\b/i.test(f.name||''));
const plannedCheckpoint=f=>f.type==='checkpoint'&&!isDayStart(f)&&!isDayFinish(f)&&f.planIncluded!==false&&!['skipped','unreachable'].includes(f.status);
const plannedFuel=f=>f.type==='fuel'&&f.planIncluded===true;
const orderedDayStops=day=>{
  const fs=dayFeatures(day),start=fs.find(isDayStart),finish=fs.find(isDayFinish);
  const middle=fs.filter(f=>plannedCheckpoint(f)||plannedFuel(f)).sort((a,b)=>(Number(a.planOrder)||Number(a.sequence)||9999)-(Number(b.planOrder)||Number(b.sequence)||9999)||String(a.name).localeCompare(String(b.name)));
  return [start,...middle,finish].filter(Boolean);
};
const plannerLine=f=>f?.geometry?.kind==='line'&&['route','track'].includes(f.type);
function keepPlannerSelection(id){state.selectedId=id;const feature=state.project.features.find(f=>f.id===id);if(feature)populateFeatureForm(feature);}
const primaryLines=day=>dayFeatures(day).filter(f=>plannerLine(f)&&(f.planRole==='primary'||f.primaryForDay===true));
const alternativeLines=day=>dayFeatures(day).filter(f=>plannerLine(f)&&f.planRole==='alternative');
function ensurePlannerMetadata(){
  for(let day=1;day<=8;day++){
    const fs=dayFeatures(day);
    fs.filter(f=>f.type==='checkpoint'&&!isDayStart(f)&&!isDayFinish(f)).sort((a,b)=>(Number(a.sequence)||9999)-(Number(b.sequence)||9999)).forEach((f,index)=>{f.planIncluded=f.planIncluded!==false;f.planOrder=Number(f.planOrder)||Number(f.sequence)||index+1;f.sequence=Number(f.sequence)||index+1;normalizeCheckpoint(f,index);});
    fs.filter(f=>f.type==='fuel').forEach(f=>{f.planIncluded=f.planIncluded===true;});
    const routes=fs.filter(f=>f.type==='route'&&f.geometry?.kind==='line'),tracks=fs.filter(f=>f.type==='track'&&f.geometry?.kind==='line');
    if(!routes.some(f=>f.planRole==='primary')&&routes.length){routes[0].planRole='primary';routes[0].primaryForDay=true;routes[0].alternativeName='Primary';routes[0].pairId||=uid();}
    if(!tracks.some(f=>f.planRole==='primary')&&tracks.length){const matching=routes.find(r=>r.planRole==='primary'&&lineGeometriesMatch(r.geometry.coordinates,tracks[0].geometry.coordinates));tracks[0].planRole='primary';tracks[0].primaryForDay=true;tracks[0].alternativeName='Primary';tracks[0].pairId=matching?.pairId||tracks[0].pairId||uid();}
  }
}
function checkpointPoints(day){return dayFeatures(day).filter(f=>f.type==='checkpoint'&&!isDayStart(f)&&!isDayFinish(f)).sort((a,b)=>(Number(a.planOrder)||Number(a.sequence)||9999)-(Number(b.planOrder)||Number(b.sequence)||9999));}
function plannerScore(day){return checkpointPoints(day).filter(plannedCheckpoint).reduce((sum,f)=>sum+(Number(f.points)||(f.extreme?21:10)),0);}
function lineName(feature){const kind=feature.routingKind==='calculated'?'calculated':feature.routingKind==='provisional'?'provisional':'manual';return `${feature.alternativeName||feature.planRole||'Unclassified'} · ${feature.type} · ${kind} · ${lineDistanceMiles(feature.geometry.coordinates).toFixed(1)} mi`;}
function markPrimaryPair(pairId,day){
  snapshot();const selected=state.project.features.find(f=>f.id===pairId);if(selected&&!selected.pairId)selected.pairId=uid();const resolved=selected?.pairId||pairId;for(const f of dayFeatures(day).filter(plannerLine)){const primary=f.pairId===resolved||f.id===pairId;f.planRole=primary?'primary':'alternative';f.primaryForDay=primary;f.alternativeName=primary?'Primary':(f.alternativeName==='Primary'?'Alternative':f.alternativeName||'Alternative');}
  saveProject(false);renderAll();
}
function renderPlannerRouteBuilder(){
  if(!$('plannerBuilder'))return;ensurePlannerMetadata();const day=activePlannerDay();
  $('plannerDayBadge').textContent=day?`Day ${day}`:'Choose a day';
  if(!day){$('plannerDaySummary').className='planner-summary empty';$('plannerDaySummary').textContent='Choose Day 1–8 to begin planning.';$('checkpointSequence').className='checkpoint-sequence empty';$('checkpointSequence').textContent='No active planning day.';$('plannerEndpoints').innerHTML='';$('routePairList').textContent='No active planning day.';$('dailyQaSummary').textContent='Choose a day to run validation.';$('dailyLegTable').innerHTML='';return;}
  const fs=dayFeatures(day),start=fs.find(isDayStart),finish=fs.find(isDayFinish),checkpoints=checkpointPoints(day),fuel=fs.filter(f=>f.type==='fuel');
  $('plannerDaySummary').className='planner-summary';$('plannerDaySummary').innerHTML=`<article><span>Checkpoints</span><strong>${checkpoints.filter(plannedCheckpoint).length}/${checkpoints.length}</strong></article><article><span>Planned points</span><strong>${plannerScore(day)}</strong></article><article><span>Routes</span><strong>${fs.filter(f=>f.type==='route').length}</strong></article><article><span>Tracks</span><strong>${fs.filter(f=>f.type==='track').length}</strong></article>`;
  $('plannerEndpoints').innerHTML=`<div><strong>Start</strong><span>${escapeHtml(start?.name||'Missing')}</span></div><div><strong>Hotel / finish</strong><span>${escapeHtml(finish?.name||'Missing')}</span></div>`;
  const sortable=[...checkpoints,...fuel].sort((a,b)=>(Number(a.planOrder)||Number(a.sequence)||9999)-(Number(b.planOrder)||Number(b.sequence)||9999));
  const sequence=$('checkpointSequence');sequence.className=sortable.length?'checkpoint-sequence':'checkpoint-sequence empty';sequence.innerHTML=sortable.length?sortable.map(f=>`<div class="sequence-row" draggable="true" data-sequence-id="${f.id}"><span class="drag-handle" title="Drag to reorder">☰</span><span class="sequence-number">${f.type==='checkpoint'?(Number(f.sequence)||'C'):'F'}</span><button type="button" data-planner-select="${f.id}"><strong>${escapeHtml(f.name)}</strong><small>${f.type==='checkpoint'?(f.extreme?'Extreme · 21 points':'Normal · 10 points'):'Fuel stop'}</small></button><label><input type="checkbox" data-plan-included="${f.id}" ${f.planIncluded!==false&&(f.type!=='fuel'||f.planIncluded===true)?'checked':''}> Plan</label></div>`).join(''):'No checkpoints or fuel stops assigned to this day.';
  wireSequenceRows(sequence,day);
  const lines=fs.filter(plannerLine);$('joinLineSelect').innerHTML='<option value="">Choose compatible line</option>'+lines.filter(f=>f.id!==state.selectedId).map(f=>`<option value="${f.id}">${escapeHtml(f.name)}</option>`).join('');
  const pairList=$('routePairList');pairList.className=lines.length?'route-pair-list':'route-pair-list empty';pairList.innerHTML=lines.length?lines.map(f=>`<div class="route-pair-row ${f.planRole==='primary'?'is-primary':''}"><span class="swatch" style="background:${COLORS[f.type]}"></span><button type="button" data-planner-select="${f.id}"><strong>${escapeHtml(f.name)}</strong><small>${escapeHtml(lineName(f))}${f.pairId?' · paired':''}</small></button><label><input type="checkbox" data-export-alt="${f.id}" ${f.exportEnabled!==false?'checked':''}> Export</label><button type="button" class="mini-button" data-make-primary="${f.pairId||f.id}">Primary</button></div>`).join(''):'No route/track plans for this day.';
  pairList.querySelectorAll('[data-planner-select]').forEach(b=>b.onclick=()=>keepPlannerSelection(b.dataset.plannerSelect));pairList.querySelectorAll('[data-export-alt]').forEach(input=>input.onchange=()=>{const f=state.project.features.find(x=>x.id===input.dataset.exportAlt);f.exportEnabled=input.checked;saveProject(false);});pairList.querySelectorAll('[data-make-primary]').forEach(b=>b.onclick=()=>markPrimaryPair(b.dataset.makePrimary,day));
  const qa=validateDayPlan(day);renderQaAndLegs(qa);
}
function wireSequenceRows(container,day){
  let dragged='';container.querySelectorAll('[data-planner-select]').forEach(b=>b.onclick=()=>selectFeature(b.dataset.plannerSelect));container.querySelectorAll('[data-plan-included]').forEach(input=>input.onchange=()=>{const f=state.project.features.find(x=>x.id===input.dataset.planIncluded);snapshot();f.planIncluded=input.checked;if(f.type==='checkpoint'&&!input.checked&&f.status==='next')f.status='planned';saveProject(false);renderAll();});
  container.querySelectorAll('.sequence-row').forEach(row=>{row.ondragstart=()=>{dragged=row.dataset.sequenceId;row.classList.add('dragging');};row.ondragend=()=>row.classList.remove('dragging');row.ondragover=e=>e.preventDefault();row.ondrop=e=>{e.preventDefault();if(!dragged||dragged===row.dataset.sequenceId)return;const ordered=[...container.querySelectorAll('.sequence-row')].map(el=>el.dataset.sequenceId),from=ordered.indexOf(dragged),to=ordered.indexOf(row.dataset.sequenceId);ordered.splice(to,0,ordered.splice(from,1)[0]);snapshot();let checkpointIndex=0;ordered.forEach((id,index)=>{const f=state.project.features.find(x=>x.id===id);f.planOrder=index+1;if(f.type==='checkpoint')f.sequence=++checkpointIndex;});saveProject(false);renderAll();setStatus(`Updated Day ${day} checkpoint sequence.`);};});
}
function plannerRouteRequest(){const day=activePlannerDay(),stops=orderedDayStops(day),coordinates=stops.map(plannerPoint);if(!day)throw new Error('Choose Day 1–8 before building a route.');if(stops.length<2)throw new Error('A day start and hotel/finish are required.');if(coordinates.some(point=>!validPoint(point)))throw new Error('One or more planned stops has invalid coordinates.');return {day,stops,coordinates};}
function replacePrimaryRoute(day,coordinates,metadata={}){snapshot();const pairId=uid();for(const f of primaryLines(day).filter(f=>f.type==='route')){f.planRole='alternative';f.primaryForDay=false;f.alternativeName=f.alternativeName==='Primary'?'Previous primary':f.alternativeName||'Previous primary';}const now=new Date().toISOString(),route={id:uid(),name:`Day ${day} ${metadata.routingKind==='provisional'?'Provisional Connection':'Primary Route'}`,type:'route',day,notes:metadata.notes||'',visible:true,source:metadata.source||'CannonMap route builder',createdAt:now,updatedAt:now,geometry:{kind:'line',coordinates:coordinates.map(point=>({...point}))},routingKind:metadata.routingKind||'manual',routingProvider:metadata.routingProvider||'',routingProfile:metadata.routingProfile||'',routingDurationMinutes:metadata.routingDurationMinutes||null,routingStops:metadata.routingStops||[],pairId,planRole:'primary',primaryForDay:true,alternativeName:'Primary',exportEnabled:true};state.project.features.push(route);saveProject(false);renderAll();keepPlannerSelection(route.id);return route;}
async function buildRouteFromSequence(){let request;try{request=plannerRouteRequest();}catch(error){return setStatus(error.message,true);}const providerId=$('plannerRoutingProvider').value,provider=ROUTING_PROVIDERS[providerId];if(!provider)return buildProvisionalRoute();const profile=$('plannerRoutingProfile').value||'driving',status=$('plannerRoutingStatus');status.className='notice';status.textContent=`Calculating Day ${request.day} with ${provider.label}…`;$('buildSequenceRouteButton').disabled=true;try{const result=await provider.calculate(request.coordinates,profile),route=replacePrimaryRoute(request.day,result.coordinates,{routingKind:'calculated',routingProvider:result.provider,routingProfile:result.profile,routingDurationMinutes:result.durationMinutes,routingStops:request.stops.map(stop=>stop.id),source:result.provider,notes:`Calculated along routable roads by ${result.provider} using ${result.profile}. Recalculate after changing checkpoint order.`});status.className='notice routing-calculated';status.textContent=`Calculated ${result.distanceMiles.toFixed(1)} mi with ${result.provider}.`;setStatus(`Calculated Day ${request.day} road route through ${request.stops.length} planned stops.`);return route;}catch(error){status.className='notice routing-provisional';status.textContent=`Routing failed: ${error.message}`;setStatus(`Road-route calculation failed. No straight line was silently substituted. ${error.message}`,true);return null;}finally{$('buildSequenceRouteButton').disabled=false;}}
function buildProvisionalRoute(){let request;try{request=plannerRouteRequest();}catch(error){return setStatus(error.message,true);}const route=replacePrimaryRoute(request.day,request.coordinates,{routingKind:'provisional',routingProvider:'none',routingStops:request.stops.map(stop=>stop.id),source:'CannonMap provisional connection',notes:'Straight provisional connection between ordered stops. This is not a calculated road route. Replace it with a calculated route or manually drawn track before navigation.'});$('plannerRoutingStatus').className='notice routing-provisional';$('plannerRoutingStatus').textContent='Straight provisional connection created. It is not a navigable road route.';setStatus(`Created a clearly labeled provisional connection for Day ${request.day}.`);return route;}
function selectedPlannerLine(){const f=state.project.features.find(x=>x.id===state.selectedId);if(!plannerLine(f)){setStatus('Select a route or track first.',true);return null;}return f;}
function reversePlannerLine(){const f=selectedPlannerLine();if(!f)return;snapshot();f.geometry.coordinates.reverse();f.updatedAt=new Date().toISOString();saveProject(false);renderAll();keepPlannerSelection(f.id);setStatus(`Reversed ${f.name}.`);}
function duplicatePlannerAlternative(){const f=selectedPlannerLine();if(!f)return;const name=$('plannerAlternativeName').value||'Alternative';snapshot();const copy=deepClean(f);copy.id=uid();copy.name=`${f.name} — ${name}`;copy.planRole=name==='Primary'?'primary':'alternative';copy.primaryForDay=name==='Primary';copy.alternativeName=name;copy.pairId=uid();copy.exportEnabled=true;copy.createdAt=copy.updatedAt=new Date().toISOString();state.project.features.push(copy);saveProject(false);renderAll();keepPlannerSelection(copy.id);setStatus(`Created ${name} alternative without changing the original.`);}
function convertRouteTrackCopy(){const f=selectedPlannerLine();if(!f)return;snapshot();const copy=deepClean(f);copy.id=uid();copy.type=f.type==='route'?'track':'route';copy.name=`${f.name} (${copy.type})`;copy.pairId=f.pairId||uid();f.pairId=copy.pairId;copy.createdAt=copy.updatedAt=new Date().toISOString();state.project.features.push(copy);saveProject(false);renderAll();keepPlannerSelection(copy.id);setStatus(`Created paired ${copy.type}; matching route/track mileage is counted once.`);}
function trimPlannerLine(which){const f=selectedPlannerLine();if(!f||f.geometry.coordinates.length<3)return setStatus('A line needs at least three points before trimming.',true);snapshot();if(which==='start')f.geometry.coordinates.shift();else f.geometry.coordinates.pop();f.updatedAt=new Date().toISOString();saveProject(false);renderAll();keepPlannerSelection(f.id);setStatus(`Trimmed ${which} of ${f.name}.`);}
function splitPlannerLine(){const f=selectedPlannerLine();if(!f)return;const index=Math.trunc(Number($('splitPointIndex').value))-1,points=f.geometry.coordinates;if(index<1||index>=points.length-1)return setStatus(`Split point must be between 2 and ${Math.max(2,points.length-1)}.`,true);snapshot();const copy=deepClean(f),now=new Date().toISOString();f.geometry.coordinates=points.slice(0,index+1);f.name=`${f.name} A`;f.updatedAt=now;copy.id=uid();copy.name=`${copy.name} B`;copy.geometry.coordinates=points.slice(index);copy.pairId=uid();copy.planRole='alternative';copy.primaryForDay=false;copy.createdAt=copy.updatedAt=now;state.project.features.push(copy);saveProject(false);renderAll();keepPlannerSelection(copy.id);setStatus('Split line into two compatible sections.');}
function orientedJoin(a,b){const options=[[a,b],[a,[...b].reverse()],[[...a].reverse(),b],[[...a].reverse(),[...b].reverse()]];options.sort((x,y)=>haversine(x[0].at(-1),x[1][0])-haversine(y[0].at(-1),y[1][0]));const best=options[0],gap=haversine(best[0].at(-1),best[1][0])/1609.344;return {points:[...best[0],...best[1].slice(gap<.01?1:0)],gap};}
function joinPlannerLines(){const f=selectedPlannerLine(),other=state.project.features.find(x=>x.id===$('joinLineSelect').value);if(!f||!plannerLine(other)||Number(f.day)!==Number(other.day))return setStatus('Choose another route or track from the same day.',true);const joined=orientedJoin(f.geometry.coordinates,other.geometry.coordinates);if(joined.gap>1)return setStatus(`Lines are ${joined.gap.toFixed(1)} miles apart and are not compatible.`,true);snapshot();f.geometry.coordinates=joined.points;f.name=`${f.name} + ${other.name}`;f.updatedAt=new Date().toISOString();state.project.features=state.project.features.filter(x=>x.id!==other.id);saveProject(false);renderAll();keepPlannerSelection(f.id);setStatus(`Joined lines${joined.gap>.05?` across a ${joined.gap.toFixed(2)} mile gap`:''}.`);}
function nearestLineCumulative(point,line){let best={distance:Infinity,miles:0},cumulative=0;const scale=Math.cos(point.lat*Math.PI/180);for(let i=1;i<line.length;i++){const a=line[i-1],b=line[i],dx=(b.lon-a.lon)*scale,dy=b.lat-a.lat,px=(point.lon-a.lon)*scale,py=point.lat-a.lat,den=dx*dx+dy*dy,t=den?Math.max(0,Math.min(1,(px*dx+py*dy)/den)):0,projected={lat:a.lat+(b.lat-a.lat)*t,lon:a.lon+(b.lon-a.lon)*t},segment=haversine(a,b),distance=haversine(point,projected);if(distance<best.distance)best={distance,miles:(cumulative+segment*t)/1609.344};cumulative+=segment;}return best;}
function dailyLegAnalysis(day,route){const stops=orderedDayStops(day);let prior=null;const rows=stops.map(stop=>{const p=plannerPoint(stop),onRoute=route?nearestLineCumulative(p,route.geometry.coordinates):null,distance=prior?(route&&onRoute?Math.max(0,onRoute.miles-prior.cumulative):haversine(prior.point,p)/1609.344):0,row={name:stop.name,type:stop.type,legMiles:distance,cumulative:onRoute?.miles??((prior?.cumulative||0)+distance),points:stop.type==='checkpoint'?(Number(stop.points)||(stop.extreme?21:10)):0};prior={point:p,cumulative:row.cumulative};return row;});let nextFuel=null;for(let index=rows.length-1;index>=0;index--){if(rows[index].type==='fuel'||rows[index].type==='hotel')nextFuel=rows[index].cumulative;rows[index].distanceToFuel=nextFuel===null?null:Math.max(0,nextFuel-rows[index].cumulative);}return rows;}
function validateDayPlan(day){
  const fs=dayFeatures(day),issues=[],start=fs.find(isDayStart),finish=fs.find(isDayFinish),routes=fs.filter(f=>f.type==='route'&&f.planRole==='primary'),tracks=fs.filter(f=>f.type==='track'&&f.planRole==='primary'),route=routes[0],track=tracks[0],checkpoints=checkpointPoints(day).filter(plannedCheckpoint);
  if(!start)issues.push({level:'error',message:'Missing day start.'});if(!finish)issues.push({level:'error',message:'Missing hotel/finish.'});
  for(const f of fs.filter(plannerLine)){if(!Array.isArray(f.geometry.coordinates)||f.geometry.coordinates.filter(validPoint).length<2)issues.push({level:'error',message:`${f.name} has fewer than two valid points.`});for(let i=1;i<f.geometry.coordinates.length;i++){const jump=haversine(f.geometry.coordinates[i-1],f.geometry.coordinates[i])/1609.344;if(jump>25)issues.push({level:'warning',message:`${f.name} has a suspicious ${jump.toFixed(1)} mi jump.`});}}
  const primary=[...routes,...tracks];for(let i=1;i<primary.length;i++){const joined=orientedJoin(primary[i-1].geometry.coordinates,primary[i].geometry.coordinates);if(joined.gap>.5)issues.push({level:'error',message:`Primary sections are disconnected by ${joined.gap.toFixed(1)} mi.`});}
  if(route?.routingKind==='provisional')issues.push({level:'error',message:'Primary route is a straight provisional connection, not a calculated road route.'});
  if(route?.routingKind==='calculated'&&!route.routingProvider)issues.push({level:'warning',message:'Calculated route is missing routing-provider metadata.'});
  if(route)for(const cp of checkpoints){const distance=pointToLineMiles(plannerPoint(cp),route.geometry.coordinates);if(distance>.5)issues.push({level:'warning',message:`${cp.name} is ${distance.toFixed(1)} mi from the primary route.`});}
  const sequences=checkpoints.map(f=>Number(f.sequence));if(new Set(sequences).size!==sequences.length||sequences.some((n,i)=>!Number.isFinite(n)||(i&&n<sequences[i-1])))issues.push({level:'error',message:'Checkpoint sequence contains duplicates or is out of order.'});
  for(const r of routes)for(const t of tracks)if(lineGeometriesMatch(r.geometry.coordinates,t.geometry.coordinates)&&r.pairId!==t.pairId)issues.push({level:'info',message:`${r.name} duplicates ${t.name}; pair them to avoid ambiguity.`});
  const unassigned=state.project.features.filter(f=>!Number(f.day)).length;if(unassigned)issues.push({level:'warning',message:`${unassigned} project features are unassigned.`});if(state.project.features.some(isProhibitedFeature))issues.push({level:'error',message:'Prohibited Old Coast Road content detected.'});
  const legs=dailyLegAnalysis(day,route),fuelLegs=[];let sinceFuel=0;for(const leg of legs){sinceFuel+=leg.legMiles;if(leg.type==='fuel'||isDayFinish(fs.find(f=>f.name===leg.name))){fuelLegs.push(sinceFuel);sinceFuel=0;}}const longestFuelLeg=fuelLegs.length?Math.max(...fuelLegs):legs.at(-1)?.cumulative||0,range=Number(state.settings.expectedMixedRange)||0;if(range&&longestFuelLeg>Math.max(0,range-Number(state.settings.reserveDistance||0)))issues.push({level:'warning',message:`Longest fuel leg ${longestFuelLeg.toFixed(1)} mi exceeds configured usable range.`});else if(!fs.some(f=>f.type==='fuel'))issues.push({level:'warning',message:'No fuel stops are selected for this day.'});
  const enabledAlternatives=alternativeLines(day).filter(f=>f.exportEnabled!==false);
  const backboneMiles=fs.filter(f=>f.type==='backbone'&&f.geometry?.kind==='line').reduce((sum,f)=>sum+lineDistanceMiles(f.geometry.coordinates),0),unassignedMiles=state.project.features.filter(f=>!Number(f.day)&&f.geometry?.kind==='line').reduce((sum,f)=>sum+lineDistanceMiles(f.geometry.coordinates),0);
  return {day,fs,start,finish,route,track,routes,tracks,checkpoints,issues,legs,longestFuelLeg,primaryRouteMiles:routes.reduce((s,f)=>s+lineDistanceMiles(f.geometry.coordinates),0),primaryTrackMiles:tracks.reduce((s,f)=>s+lineDistanceMiles(f.geometry.coordinates),0),selectedPrimaryMiles:planningMileage(primary),alternateMiles:planningMileage(enabledAlternatives),backboneMiles,unassignedMiles,points:plannerScore(day)};
}
function renderQaAndLegs(qa){const box=$('dailyQaSummary');box.className=`daily-qa ${qa.issues.some(i=>i.level==='error')?'has-errors':'is-ready'}`;box.innerHTML=`<div class="qa-metrics"><article><span>Primary route</span><strong>${qa.primaryRouteMiles.toFixed(1)} mi</strong></article><article><span>Primary track</span><strong>${qa.primaryTrackMiles.toFixed(1)} mi</strong></article><article><span>Selected primary plan</span><strong>${qa.selectedPrimaryMiles.toFixed(1)} mi</strong></article><article><span>Alternatives</span><strong>${qa.alternateMiles.toFixed(1)} mi</strong></article><article><span>Backbone / reference</span><strong>${qa.backboneMiles.toFixed(1)} mi</strong></article><article><span>Unassigned lines</span><strong>${qa.unassignedMiles.toFixed(1)} mi</strong></article><article><span>Longest fuel leg</span><strong>${qa.longestFuelLeg.toFixed(1)} mi</strong></article></div><ul>${qa.issues.length?qa.issues.map(i=>`<li class="qa-${i.level}">${escapeHtml(i.message)}</li>`).join(''):'<li class="qa-ok">No validation problems detected.</li>'}</ul>`;
  $('dailyLegTable').innerHTML=qa.legs.length?`<table><thead><tr><th>Stop</th><th>Type</th><th>Leg</th><th>Cumulative</th><th>Next fuel/finish</th><th>Points</th></tr></thead><tbody>${qa.legs.map(row=>`<tr><td>${escapeHtml(row.name)}</td><td>${escapeHtml(row.type)}</td><td>${row.legMiles.toFixed(1)} mi</td><td>${row.cumulative.toFixed(1)} mi</td><td>${row.distanceToFuel===null?'—':`${row.distanceToFuel.toFixed(1)} mi`}</td><td>${row.points||'—'}</td></tr>`).join('')}</tbody></table>`:'<p class="helper-text">No planned stops available for leg analysis.</p>';
}
function plannerExportFeatures(days){const set=new Set(days.map(Number));return state.project.features.filter(f=>set.has(Number(f.day))).filter(f=>{if(f.geometry?.kind==='point')return isDayStart(f)||isDayFinish(f)||plannedCheckpoint(f)||plannedFuel(f);if(plannerLine(f))return f.planRole==='primary'||(f.planRole==='alternative'&&f.exportEnabled===true);return false;});}
function plannerLineExtensions(f){return `<extensions><cannonmap:day>${Number(f.day)||0}</cannonmap:day><cannonmap:planRole>${xmlEscape(f.planRole||'')}</cannonmap:planRole><cannonmap:alternative>${xmlEscape(f.alternativeName||'')}</cannonmap:alternative><cannonmap:pairId>${xmlEscape(f.pairId||'')}</cannonmap:pairId><cannonmap:routingKind>${xmlEscape(f.routingKind||'manual')}</cannonmap:routingKind><cannonmap:routingProvider>${xmlEscape(f.routingProvider||'')}</cannonmap:routingProvider><cannonmap:routingProfile>${xmlEscape(f.routingProfile||'')}</cannonmap:routingProfile><cannonmap:exportEnabled>${f.exportEnabled===false?'false':'true'}</cannonmap:exportEnabled></extensions>`;}
function plannerGpx(days,title){const fs=filterProhibitedFeatures(plannerExportFeatures(days),'planner GPX export');const w=fs.filter(f=>f.geometry.kind==='point').map(f=>{const p=plannerPoint(f);return `  <wpt lat="${p.lat.toFixed(8)}" lon="${p.lon.toFixed(8)}"><name>${xmlEscape(f.name)}</name><desc>${xmlEscape(f.notes||'')}</desc><type>${xmlEscape(f.type)}</type><extensions><cannonmap:day>${Number(f.day)||0}</cannonmap:day><cannonmap:sequence>${Number(f.sequence)||0}</cannonmap:sequence><cannonmap:points>${f.type==='checkpoint'?(Number(f.points)||(f.extreme?21:10)):0}</cannonmap:points><cannonmap:extreme>${f.extreme?'true':'false'}</cannonmap:extreme><cannonmap:planned>${f.planIncluded!==false?'true':'false'}</cannonmap:planned><cannonmap:planOrder>${Number(f.planOrder)||0}</cannonmap:planOrder><cannonmap:plannerRole>${xmlEscape(f.plannerRole||'')}</cannonmap:plannerRole></extensions></wpt>`;}).join('\n');const r=fs.filter(f=>f.type==='route').map(f=>`  <rte><name>${xmlEscape(f.name)}</name><desc>${xmlEscape(f.notes||'')}</desc>${plannerLineExtensions(f)}${f.geometry.coordinates.map(p=>`<rtept lat="${p.lat.toFixed(8)}" lon="${p.lon.toFixed(8)}" />`).join('')}</rte>`).join('\n');const t=fs.filter(f=>f.type==='track').map(f=>`  <trk><name>${xmlEscape(f.name)}</name><desc>${xmlEscape(f.notes||'')}</desc>${plannerLineExtensions(f)}<trkseg>${f.geometry.coordinates.map(p=>`<trkpt lat="${p.lat.toFixed(8)}" lon="${p.lon.toFixed(8)}" />`).join('')}</trkseg></trk>`).join('\n');return `<?xml version="1.0" encoding="UTF-8"?>\n<gpx version="1.1" creator="CannonMap ${APP_VERSION}" xmlns="http://www.topografix.com/GPX/1/1" xmlns:cannonmap="https://cannonmap.pages.dev/schema/1"><metadata><name>${xmlEscape(title)}</name><time>${new Date().toISOString()}</time></metadata>\n${w}\n${r}\n${t}\n</gpx>`;}
function exportPlannerDays(days,separate=false){if(separate){for(const day of days)downloadBlob(plannerGpx([day],`${state.project.name} Day ${day}`),`${safeFilename(state.project.name)}-day-${day}.gpx`,'application/gpx+xml');setStatus('Exported eight separate daily GPX files.');return;}const suffix=days.length===1?`day-${days[0]}`:'master';downloadBlob(plannerGpx(days,days.length===1?`${state.project.name} Day ${days[0]}`:state.project.name),`${safeFilename(state.project.name)}-${suffix}.gpx`,'application/gpx+xml');setStatus(`Exported ${suffix} planner GPX.`);}
function qaRows(){return [1,2,3,4,5,6,7,8].map(day=>{const q=validateDayPlan(day);return {Day:day,Checkpoints:q.checkpoints.length,Routes:q.fs.filter(f=>f.type==='route').length,Tracks:q.fs.filter(f=>f.type==='track').length,'Primary route miles':q.primaryRouteMiles.toFixed(1),'Primary track miles':q.primaryTrackMiles.toFixed(1),'Selected primary miles':q.selectedPrimaryMiles.toFixed(1),'Alternate miles':q.alternateMiles.toFixed(1),'Backbone miles':q.backboneMiles.toFixed(1),'Unassigned line miles':q.unassignedMiles.toFixed(1),'Unassigned project items':state.project.features.filter(f=>!Number(f.day)).length,'Disconnected sections':q.issues.filter(i=>/disconnected/i.test(i.message)).length,'Checkpoint sequence':q.checkpoints.map(f=>f.name).join(' > '),'Planned points':q.points,'Longest fuel leg':q.longestFuelLeg.toFixed(1),Issues:q.issues.map(i=>i.message).join(' | ')};});}
function exportQaReport(){const rows=qaRows(),headers=Object.keys(rows[0]),csv=[headers.map(csvEscape).join(','),...rows.map(r=>headers.map(h=>csvEscape(r[h])).join(','))].join('\n');downloadBlob(csv,`${safeFilename(state.project.name)}-qa-report.csv`,'text/csv;charset=utf-8');setStatus('Exported eight-day QA report.');}
function wirePlannerRouteBuilder(){if(!$('plannerBuilder'))return;$('buildSequenceRouteButton').onclick=buildRouteFromSequence;$('buildProvisionalRouteButton').onclick=buildProvisionalRoute;$('plannerRoutingProvider').onchange=()=>{const provisional=$('plannerRoutingProvider').value==='provisional';$('plannerRoutingProfile').disabled=provisional;$('buildSequenceRouteButton').disabled=provisional;$('plannerRoutingStatus').textContent=provisional?'Provider disabled. Only an explicitly labeled provisional connection can be created.':'OSRM public demo ready. Online driving/road routing only.';};$('editPlannerLineButton').onclick=()=>{const f=selectedPlannerLine();if(f)editSelectedGeometry();};$('reversePlannerLineButton').onclick=reversePlannerLine;$('duplicateAlternativeButton').onclick=duplicatePlannerAlternative;$('convertRouteTrackButton').onclick=convertRouteTrackCopy;$('trimLineStartButton').onclick=()=>trimPlannerLine('start');$('trimLineEndButton').onclick=()=>trimPlannerLine('end');$('splitPlannerLineButton').onclick=splitPlannerLine;$('joinPlannerLineButton').onclick=joinPlannerLines;$('exportActiveDayButton').onclick=()=>{const day=activePlannerDay();if(day)exportPlannerDays([day]);else setStatus('Choose an active day first.',true);};$('exportEightDaysButton').onclick=()=>exportPlannerDays([1,2,3,4,5,6,7,8],true);$('exportMasterPlannerButton').onclick=()=>exportPlannerDays([1,2,3,4,5,6,7,8]);$('exportQaButton').onclick=exportQaReport;}

window.CannonMapPlannerTest={ROUTING_PROVIDERS,orderedDayStops,plannerScore,buildRouteFromSequence,buildProvisionalRoute,orientedJoin,validateDayPlan,plannerGpx,qaRows,projectFeatures:()=>deepClean(state.project.features)};
