import assert from 'node:assert/strict';import test from 'node:test';
import {createCheckpointCameraWorkflow} from '../src/application/checkpoint-camera-workflow.js';

const ids=['10000000-0000-4000-8000-000000000001','10000000-0000-4000-8000-000000000002','10000000-0000-4000-8000-000000000003','10000000-0000-4000-8000-000000000004'];
function harness({capture}={}){let index=0;const events=[],completed=[];const workflow=createCheckpointCameraWorkflow({
  mediaRepository:{markPairComplete:async(pairId,eventId)=>completed.push({pairId,eventId})},
  photoEvidence:{capture:capture||(async input=>({mediaGroupId:`group-${input.context.cameraRole}`,original:{mediaId:`${input.context.cameraRole}-original`},evidence:{mediaId:`${input.context.cameraRole}-evidence`},metadata:input.context}))},
  journal:{appendEventIdempotent:async event=>{events.push(event);return event;}},clock:{iso:()=> '2026-08-08T12:00:00.000Z'},createId:()=>ids[index++],onState:()=>{}
});workflow.start({projectId:'project',checkpoint:{id:'cp',name:'1.1',day:1,photoRequired:true},journalEvent:{eventId:'arrival'},required:true});return {workflow,events,completed};}

test('front and rear share one pair identity and completion requires four durable assets',async()=>{const {workflow,events,completed}=harness(),pairId=workflow.getState().pairId;await workflow.addSide('front',new Blob(['front']));assert.equal(workflow.getState().status,'rear_required');assert.equal(workflow.finish(),null);await workflow.addSide('rear',new Blob(['rear']));const state=workflow.getState();assert.equal(state.pairId,pairId);assert.equal(state.status,'ready');assert.equal(events.length,1);assert.equal(events[0].references.pairId,pairId);assert.deepEqual(events[0].attachments.photos.map(row=>row.mediaId),['front-original','front-evidence','rear-original','rear-evidence']);assert.equal(completed[0].pairId,pairId);assert.equal(workflow.finish().status,'ready');});

test('front success and rear cancellation remain PHOTO_REQUIRED and resume without front recapture',async()=>{const {workflow}=harness();await workflow.addSide('front',new Blob(['front']));workflow.cancel('rear');assert.match(workflow.getState().error,/Front captured safely/);assert.equal(workflow.getState().status,'rear_required');assert.equal(workflow.finish(),null);workflow.retry();assert.equal(workflow.getState().status,'rear_required');await workflow.addSide('rear',new Blob(['rear']));assert.equal(workflow.getState().status,'ready');});

test('restart restores front and resumes the missing rear side with the same pairId',async()=>{const first=harness();const pairId=first.workflow.getState().pairId,journalId=first.workflow.getState().pairJournalEventId;await first.workflow.addSide('front',new Blob(['front']));let index=0;const restored=createCheckpointCameraWorkflow({mediaRepository:{markPairComplete:async()=>4},photoEvidence:{capture:async input=>({original:{mediaId:'rear-original'},evidence:{mediaId:'rear-evidence'},metadata:input.context})},journal:{appendEventIdempotent:async event=>event},clock:{iso:()=> '2026-08-08T12:01:00.000Z'},createId:()=>ids[index++]});restored.start({projectId:'project',checkpoint:{id:'cp',name:'1.1'},journalEvent:{eventId:'arrival'},pairId,pairJournalEventId:journalId});restored.restoreSide('front',first.workflow.getState().sides.front);assert.equal(restored.getState().status,'rear_required');await restored.addSide('rear',new Blob(['rear']));assert.equal(restored.getState().pairId,pairId);assert.equal(restored.getState().status,'ready');});

test('persistence failure never reports pair success or completes the objective',async()=>{const {workflow,events}=harness({capture:async()=>{throw new DOMException('Quota full','QuotaExceededError');}});await assert.rejects(()=>workflow.addSide('front',new Blob(['front'])),error=>error.name==='QuotaExceededError');assert.equal(workflow.getState().status,'failed');assert.equal(workflow.finish(),null);assert.equal(events[0].eventType,'media_storage_failure');});
