import test from 'node:test';import assert from 'node:assert/strict';
import {stableCompetitorId,normalizeTrailPoints,segmentTrail,trailStatus,mergeCompetitorSnapshots,buildTacticalClusters} from '../src/domain/competitors/trails.js';
const now=Date.parse('2026-08-04T18:00:00Z'),p=(minute,lat=30,lon=-90,extra={})=>({lat,lon,time:new Date(now+minute*60000).toISOString(),...extra});
test('stable identities prevent cross-rider connections',()=>{assert.equal(stableCompetitorId({competitorId:7}),stableCompetitorId({id_competitor:7}));const result=mergeCompetitorSnapshots([],[{id:'7',points:[p(-2)]},{id:'8',points:[p(-1,31)]}],{now});assert.equal(result.competitors.length,2);assert.deepEqual(result.competitors.map(r=>r.points.length),[1,1]);});
test('out-of-order points sort and duplicates disappear deterministically',()=>{const points=normalizeTrailPoints([p(-1),p(-3),p(-1)],{now});assert.equal(points.length,2);assert.ok(Date.parse(points[0].time)<Date.parse(points[1].time));});
test('sessions, time gaps, and impossible jumps create separate segments',()=>{assert.equal(segmentTrail([p(-10,30,-90,{sessionId:'a'}),p(-9,30.001,-90,{sessionId:'a'}),p(-8,30.002,-90,{sessionId:'b'})]).length,2);assert.equal(segmentTrail([p(-60),p(-20,30.001)]).length,2);assert.equal(segmentTrail([p(-2),p(-1,40,-80)]).length,2);});
test('repeated polling is idempotent and history remains bounded',()=>{let competitors=[];for(let poll=0;poll<20;poll++)competitors=mergeCompetitorSnapshots(competitors,[{id:'7',points:Array.from({length:1000},(_,i)=>p(-i/10,30+i/1e6,-90))}],{now,maxPoints:500}).competitors;assert.equal(competitors.length,1);assert.equal(competitors[0].points.length,500);});
test('freshness, motion, speed, and direction are evidence based',()=>{const live=trailStatus([p(-2),p(-1,30.01,-90)],{now});assert.equal(live.status,'live');assert.equal(live.motion,'moving');assert.ok(Number.isFinite(live.speedMph));const undated=trailStatus([],{now});assert.deepEqual([undated.status,undated.speedMph,undated.direction],['offline',null,null]);});
test('tactical clusters contain only nearby live riders',()=>{const clusters=buildTacticalClusters([{id:'7',name:'A',points:[p(-1,30,-90)]},{id:'8',name:'B',points:[p(-1,30.0005,-90)]},{id:'9',name:'C',points:[p(-1,31,-90)]}],{now});assert.equal(clusters.length,1);assert.deepEqual(clusters[0].riders.map(r=>r.id),['7','8']);});
