import test from 'node:test';import assert from 'node:assert/strict';import {webcrypto} from 'node:crypto';
import {validateFinalizedProject,createFinalizedEnvelope,verifyFinalizedEnvelope,executionCleanProject} from '../src/domain/projects/finalized.js';
import {createFinalizedProjectService} from '../src/application/finalized-project-service.js';

const features=Array.from({length:31},(_,index)=>[{id:`cp-${index+1}`,type:'checkpoint',name:`${index+1}.1`,day:index+1,sequence:1,points:10,photoRequired:true,notes:'Rider note',doNotStop:index===0,geometry:{kind:'point',coordinates:[{lat:30+index/100,lon:-90}]}},{id:`hotel-${index+1}`,type:'hotel',name:`${index+1}.2 Hotel`,day:index+1,sequence:2,geometry:{kind:'point',coordinates:[{lat:30+index/100,lon:-89.9}]}}]).flat();
const project={projectId:'america-250-plan',id:'america-250-plan',schemaVersion:1,name:'America 250 2026',features:[...features,{id:'route',type:'route',name:'Optimized',day:1,geometry:{kind:'line',coordinates:[{lat:30,lon:-90},{lat:30.1,lon:-90.1}]}},{id:'backbone',type:'backbone',name:'Backbone',day:1,garminName:'A250-D1',geometry:{kind:'line',coordinates:[{lat:30,lon:-90},{lat:30.2,lon:-90.2}]}}],settings:{rallyEventId:'15',radarEnabled:true},journal:[{eventId:'x'}],analytics:{x:1},photos:[{id:'photo'}],rallyState:{active:true}};

test('31-day finalized plan validates without changing deterministic order',()=>{const report=validateFinalizedProject(project);assert.equal(report.valid,true);assert.equal(report.counts.days,31);assert.deepEqual(executionCleanProject(project).features.map(f=>f.id),project.features.map(f=>f.id));});
test('validation catches duplicate identities, sequences, coordinates, and hotel relationships',()=>{const broken=structuredClone(project);broken.features.push({...broken.features[0]});broken.features[2].sequence=1;broken.features[4].geometry.coordinates[0].lat=999;const report=validateFinalizedProject(broken);assert.equal(report.valid,false);assert.ok(report.errors.some(e=>e.code==='DUPLICATE_FEATURE_ID'));assert.ok(report.errors.some(e=>e.code==='DUPLICATE_SEQUENCE'));assert.ok(report.errors.some(e=>e.code==='POINT_COORDINATES_INVALID'));});
test('portable finalized envelope verifies checksums and excludes execution state',async()=>{const envelope=await createFinalizedEnvelope({project,settings:project.settings,applicationVersion:'0.7.1',buildId:'test',finalizedAt:'2026-08-04T18:00:00Z',crypto:webcrypto});const verified=await verifyFinalizedEnvelope(envelope.files,{crypto:webcrypto});assert.equal(verified.valid,true);assert.equal(verified.project.journal,undefined);assert.equal(verified.project.features[0].status,undefined);const corrupt={...envelope.files,'project.json':envelope.files['project.json'].replace('10','11')};await assert.rejects(()=>verifyFinalizedEnvelope(corrupt,{crypto:webcrypto}),error=>error.code==='FINALIZED_CHECKSUM_FAILED');});
test('immutable master produces isolated execution identities and package type stays distinct',async()=>{let stored=null,created=null;const repository={get:async()=>stored,create:async record=>(stored=structuredClone(record))},lifecycle={flush:async()=>{},createProject:async input=>{created=structuredClone(input);return created;}},service=createFinalizedProjectService({repository,projectLifecycle:lifecycle,createId:()=> 'execution-new',clock:{iso:()=> '2026-08-04T18:00:00Z'},applicationVersion:'0.7.1',buildId:'test',crypto:webcrypto});const output=await service.exportFinalized(project,project.settings),master=await service.importMaster(output.blob),copy=await service.createExecutionCopy(master.masterId);assert.equal(stored.immutable,true);assert.equal(stored.project.projectId,'america-250-plan');assert.equal(copy.projectId,'execution-new');assert.equal(copy.finalizedMasterReference.sourceProjectId,'america-250-plan');assert.equal(stored.project.projectId,'america-250-plan');assert.equal(output.manifest.exportType,'finalized-project');});
