import test from 'node:test';import assert from 'node:assert/strict';
import {configuredProjectDays,nextConfiguredDay} from '../src/domain/journey/days.js';
import {createMissionStorageService,isQuotaExceeded} from '../src/application/mission-storage-service.js';
import {createJourneyMediaService} from '../src/application/journey-media-service.js';
import {readStoredDayPackage,readStoredProjectPackage} from '../src/application/journey-package-restore.js';
import {createPhotoExportService,createStoredZip} from '../src/application/photo-export-service.js';
import {readStoredZip} from '../src/application/portable-zip.js';

test('configured journey days are arbitrary and nonconsecutive',()=>{const project={features:[{day:31},{day:1},{day:17},{day:31},{day:0}]};assert.deepEqual(configuredProjectDays(project),[1,17,31]);assert.equal(nextConfiguredDay(project,1),17);assert.equal(nextConfiguredDay(project,31),0);});

test('storage estimate remains project scoped and never mutates media',async()=>{const records=[{projectId:'a',role:'original',size:10,evidenceStatus:'complete',capturedAt:'2'},{projectId:'a',role:'evidence',size:8},{projectId:'b',role:'original',size:20,capturedAt:'1'}],service=createMissionStorageService({mediaRepository:{listAllPhotos:async()=>records},storageManager:{estimate:async()=>({usage:50,quota:1000})}}),result=await service.estimate('a');assert.equal(result.projectMediaSize,18);assert.equal(result.totalMediaSize,38);assert.equal(result.projectPhotoCount,1);assert.equal(records.length,3);assert.equal(isQuotaExceeded({name:'QuotaExceededError'}),true);});

test('cross-project media index keeps references isolated without copying blobs',async()=>{const blob=new Blob(['one']),service=createJourneyMediaService({mediaRepository:{listAllPhotos:async()=>[{mediaId:'m',projectId:'b',metadata:{dayNumber:2},capturedAt:'x',blob}]},projectLifecycle:{listProjects:async()=>[{projectId:'a',name:'A'},{projectId:'b',name:'B'}]}}),index=await service.index();assert.equal(index[0].projectName,'B');assert.equal(index[0].uri,'media://m');assert.equal('blob' in index[0],false);});

test('large export fails before reading blobs and cannot silently produce a partial archive',async()=>{let read=false;const blob={size:101,arrayBuffer:async()=>{read=true;return new ArrayBuffer(101);}};await assert.rejects(()=>createStoredZip([{name:'large.jpg',blob}],{maxBytes:100}),error=>error.code==='PHOTO_EXPORT_TOO_LARGE');assert.equal(read,false);});

test('day and project backup packages include native media and camera audit metadata',async()=>{const camera={requestedCamera:'front',actualCamera:'unknown',cameraSelectionHonored:'unknown',captureMethod:'file-input',captureTimestamp:'2026-08-05T12:00:00Z'},metadata={dayNumber:31,...camera},records=[{mediaId:'o',projectId:'p',role:'original',name:'Original.jpg',size:6,blob:new Blob(['native']),metadata},{mediaId:'e',projectId:'p',role:'evidence',name:'Evidence.jpg',size:8,blob:new Blob(['evidence']),metadata}],service=createPhotoExportService({repository:{listProjectPhotos:async()=>records,getMedia:async id=>records.find(item=>item.mediaId===id)}}),day=await service.dayBackup('p',31,{journal:[{eventId:'j',projectId:'p',metadata:{dayNumber:31,...camera}}],project:{projectId:'p',name:'Trip',features:[{id:'cp',day:31,status:'collected'}]}}),project=await service.projectBackup('p',{journal:[{eventId:'j',metadata:camera}],project:{name:'Trip'},settings:{radar:true}}),dayFiles=await readStoredZip(day.blob),projectFiles=await readStoredZip(project.blob),dayIndex=JSON.parse(dayFiles['manifest/media-index.json']),projectIndex=JSON.parse(projectFiles['media-index.json']);assert.deepEqual(dayIndex[0].metadata,metadata);assert.deepEqual(projectIndex[1].metadata,metadata);assert.match(dayFiles['journal/Daily_Journal.json'],/requestedCamera/);assert.equal(day.manifest.originalCount,1);assert.equal(day.verified,true);assert.equal(project.manifest.evidenceCount,1);});

test('project package round-trip preserves exact native media bytes',async()=>{const records=[{mediaId:'o',projectId:'p',role:'original',name:'Original.jpg',size:6,mimeType:'image/jpeg',blob:new Blob(['native']),metadata:{dayNumber:31}}],service=createPhotoExportService({repository:{listProjectPhotos:async()=>records}}),archive=await service.projectBackup('p',{project:{projectId:'p',name:'Trip'},journal:[],settings:{}}),payload=await readStoredProjectPackage(archive.blob);assert.equal(payload.project.projectId,'p');assert.equal(await payload.media[0].blob.text(),'native');});

test('day package checksum rejects modified media bytes',async()=>{const record={mediaId:'o',projectId:'p',role:'original',name:'Original.jpg',size:6,mimeType:'image/jpeg',blob:new Blob(['native']),metadata:{dayNumber:31}},service=createPhotoExportService({repository:{listProjectPhotos:async()=>[record]}}),archive=await service.dayBackup('p',31,{project:{projectId:'p',name:'Trip',features:[{id:'cp',day:31}]}}),bytes=new Uint8Array(await archive.blob.arrayBuffer()),needle=new TextEncoder().encode('native');let offset=-1;for(let index=0;index<=bytes.length-needle.length;index++)if(needle.every((value,part)=>bytes[index+part]===value)){offset=index;break;}assert.ok(offset>=0);bytes[offset]^=1;await assert.rejects(()=>readStoredDayPackage(new Blob([bytes])),/checksum failed/);});
