import test from 'node:test';import assert from 'node:assert/strict';
import {configuredProjectDays,nextConfiguredDay} from '../src/domain/journey/days.js';
import {createMissionStorageService,isQuotaExceeded} from '../src/application/mission-storage-service.js';
import {createJourneyMediaService} from '../src/application/journey-media-service.js';
import {readStoredProjectPackage} from '../src/application/journey-package-restore.js';
import {createPhotoExportService,createStoredZip} from '../src/application/photo-export-service.js';

test('configured journey days are arbitrary and nonconsecutive',()=>{const project={features:[{day:31},{day:1},{day:17},{day:31},{day:0}]};assert.deepEqual(configuredProjectDays(project),[1,17,31]);assert.equal(nextConfiguredDay(project,1),17);assert.equal(nextConfiguredDay(project,31),0);});

test('storage estimate remains project scoped and never mutates media',async()=>{const records=[{projectId:'a',role:'original',size:10,evidenceStatus:'complete',capturedAt:'2'},{projectId:'a',role:'evidence',size:8},{projectId:'b',role:'original',size:20,capturedAt:'1'}],service=createMissionStorageService({mediaRepository:{listAllPhotos:async()=>records},storageManager:{estimate:async()=>({usage:50,quota:1000})}}),result=await service.estimate('a');assert.equal(result.projectMediaSize,18);assert.equal(result.totalMediaSize,38);assert.equal(result.projectPhotoCount,1);assert.equal(records.length,3);assert.equal(isQuotaExceeded({name:'QuotaExceededError'}),true);});

test('cross-project media index keeps references isolated without copying blobs',async()=>{const blob=new Blob(['one']),service=createJourneyMediaService({mediaRepository:{listAllPhotos:async()=>[{mediaId:'m',projectId:'b',metadata:{dayNumber:2},capturedAt:'x',blob}]},projectLifecycle:{listProjects:async()=>[{projectId:'a',name:'A'},{projectId:'b',name:'B'}]}}),index=await service.index();assert.equal(index[0].projectName,'B');assert.equal(index[0].uri,'media://m');assert.equal('blob' in index[0],false);});

test('large export fails before reading blobs and cannot silently produce a partial archive',async()=>{let read=false;const blob={size:101,arrayBuffer:async()=>{read=true;return new ArrayBuffer(101);}};await assert.rejects(()=>createStoredZip([{name:'large.jpg',blob}],{maxBytes:100}),error=>error.code==='PHOTO_EXPORT_TOO_LARGE');assert.equal(read,false);});

test('day and project backup packages include native media and audit manifests',async()=>{const records=[{mediaId:'o',projectId:'p',role:'original',name:'Original.jpg',size:6,blob:new Blob(['native']),metadata:{dayNumber:31}},{mediaId:'e',projectId:'p',role:'evidence',name:'Evidence.jpg',size:8,blob:new Blob(['evidence']),metadata:{dayNumber:31}}],service=createPhotoExportService({repository:{listProjectPhotos:async()=>records,getMedia:async id=>records.find(item=>item.mediaId===id)}}),day=await service.dayBackup('p',31,{journal:[{eventId:'j'}],project:{name:'Trip',features:[]}}),project=await service.projectBackup('p',{journal:[{eventId:'j'}],project:{name:'Trip'},settings:{radar:true}}),decode=async blob=>new TextDecoder().decode(await blob.arrayBuffer());assert.match(await decode(day.blob),/Daily_Journal\.json/);assert.match(await decode(project.blob),/project-manifest\.json/);assert.equal(day.manifest.originalCount,1);assert.equal(project.manifest.evidenceCount,1);});

test('project package round-trip preserves exact native media bytes',async()=>{const records=[{mediaId:'o',projectId:'p',role:'original',name:'Original.jpg',size:6,mimeType:'image/jpeg',blob:new Blob(['native']),metadata:{dayNumber:31}}],service=createPhotoExportService({repository:{listProjectPhotos:async()=>records}}),archive=await service.projectBackup('p',{project:{projectId:'p',name:'Trip'},journal:[],settings:{}}),payload=await readStoredProjectPackage(archive.blob);assert.equal(payload.project.projectId,'p');assert.equal(await payload.media[0].blob.text(),'native');});
