import {test,expect} from '@playwright/test';

test('verified Day Backup round-trips Project, state, Journal, pair identity, filenames, and exact bytes into clean IndexedDB',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='iPhone 13 portrait');await page.goto('/');
  const result=await page.evaluate(async suffix=>{
    const infra=await import('/src/infrastructure/indexeddb/index.js'),exports=await import('/src/application/photo-export-service.js'),restoreModule=await import('/src/application/journey-package-restore.js'),open=name=>infra.openIndexedDbV2({indexedDB,featureFlags:{isEnabled:()=>true},databaseName:name}),sourceDb=await open(`source-${suffix}`),sourceRestore=infra.createJourneyRestoreRepository({database:sourceDb}),bytes=['front-original','front-evidence','rear-original','rear-evidence'],roles=[['front','original'],['front','evidence'],['rear','original'],['rear','evidence']],media=roles.map(([cameraRole,role],index)=>({mediaId:`m${index}`,projectId:'project',checkpointId:'hotel',journalEventId:'photo',pairId:'pair-1',pairStatus:'complete',cameraRole,role,name:`${cameraRole}-${role}.jpg`,mimeType:'image/jpeg',size:bytes[index].length,metadata:{dayNumber:9,objectiveType:'hotel',pairId:'pair-1',cameraRole},blob:new Blob([bytes[index]],{type:'image/jpeg'})})),project={projectId:'project',id:'project',name:'America 250 – 2026',features:[{id:'hotel',type:'hotel',day:9,status:'collected',points:50,photoPairId:'pair-1'}],rallyExecution:{days:{9:{dayNumber:9,status:'complete',score:50}}}},journal=[{eventId:'arrival',projectId:'project',eventType:'hotel_arrival',metadata:{dayNumber:9}},{eventId:'photo',projectId:'project',eventType:'photo_added',metadata:{dayNumber:9,objectiveType:'hotel'},references:{pairId:'pair-1'}},{eventId:'finished',projectId:'project',eventType:'day_finished',metadata:{dayNumber:9}}];
    await sourceRestore.restoreNew({project,journal,media});const sourceMedia=infra.createMissionMediaRepository({database:sourceDb,createId:()=>'',clock:{iso:()=>''}}),service=exports.createPhotoExportService({repository:sourceMedia}),archive=await service.dayBackup('project',9,{project,journal,settings:{rallyDays:{9:{status:'complete',score:50}}},applicationVersion:'test',buildId:'roundtrip'});sourceDb.close();
    const targetDb=await open(`target-${suffix}`),restore=restoreModule.createJourneyPackageRestoreService({repository:infra.createJourneyRestoreRepository({database:targetDb})}),payload=await restore.restoreDay(archive.blob),targetMedia=infra.createMissionMediaRepository({database:targetDb,createId:()=>'',clock:{iso:()=>''}}),restoredMedia=await targetMedia.listProjectPhotos('project'),tx=targetDb.transaction(['projectRecords','journalEvents'],'readonly'),request=(store,key)=>new Promise((resolve,reject)=>{const r=key?tx.objectStore(store).get(key):tx.objectStore(store).getAll();r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);}),restoredProject=await request('projectRecords','project'),restoredJournal=await request('journalEvents'),restoredBytes=await Promise.all(restoredMedia.sort((a,b)=>a.mediaId.localeCompare(b.mediaId)).map(async row=>await row.blob.text()));targetDb.close();return {filename:archive.filename,verified:archive.verified,project:restoredProject,journal:restoredJournal,media:restoredMedia.map(({blob,binaryData,...row})=>row),bytes:restoredBytes,manifest:payload.manifest};
  },`${testInfo.project.name}-${Date.now()}`);
  expect(result.filename).toBe('Day09_Backup.cmapday.zip');expect(result.verified).toBeTruthy();expect(result.project.features[0]).toMatchObject({id:'hotel',status:'collected',photoPairId:'pair-1'});expect(result.project.rallyExecution.days['9']).toMatchObject({status:'complete',score:50});expect(result.journal).toHaveLength(3);expect(result.media).toHaveLength(4);expect(new Set(result.media.map(item=>item.pairId))).toEqual(new Set(['pair-1']));expect(result.bytes).toEqual(['front-original','front-evidence','rear-original','rear-evidence']);expect(result.manifest.mediaCount).toBe(4);
});
