import {expect,test} from '@playwright/test';

const legacySession={schemaVersion:2,sessionId:'legacy-day-1',projectId:'legacy-project',rallyId:'rally',dayId:'rally-day-1',dayNumber:1,calendarDate:'2026-08-17',runNumber:1,status:'active',startedAt:'2026-08-17T13:00:00.000Z',checkpointStates:{cp1:{status:'photo_required',scoreAwarded:0}},pendingEvidence:{schemaVersion:1,entries:[]},legacy:true,origin:'schema-v1-day-execution'};
const project={projectId:'legacy-project',id:'legacy-project',name:'Legacy Rally',features:[{id:'cp1',type:'checkpoint',day:1,name:'1.1',status:'photo_required'},{id:'cp2',type:'checkpoint',day:2,name:'2.1',status:'upcoming'}],rallyExecution:{schemaVersion:2,activeSessionId:'legacy-day-1',sessions:{'legacy-day-1':legacySession},daySessions:{1:['legacy-day-1']},days:{1:{dayNumber:1,sessionId:'legacy-day-1',status:'active'}}}};

test('real IndexedDB Day Backup includes only legitimate legacy unscoped Project/day media',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='Android landscape');
  await page.goto('/');
  const result=await page.evaluate(async({project,legacySession})=>{
    const infra=await import('/src/infrastructure/indexeddb/index.js'),exports=await import('/src/application/photo-export-service.js'),restore=await import('/src/application/journey-package-restore.js'),database=await infra.openIndexedDbV2({indexedDB,featureFlags:{isEnabled:()=>true},databaseName:`legacy-manual-${Date.now()}-${Math.random()}`}),repository=infra.createJourneyRestoreRepository({database});
    const makeMedia=(mediaId,dayNumber,sessionId=null)=>({mediaId,projectId:'legacy-project',...(sessionId?{sessionId}:{}),checkpointId:`cp${dayNumber}`,journalEventId:`event-${mediaId}`,role:'original',cameraRole:'rear',name:`${mediaId}.jpg`,mimeType:'image/jpeg',metadata:{dayNumber,...(sessionId?{sessionId}:{})},blob:new Blob([mediaId],{type:'image/jpeg'})}),makeEvent=(eventId,dayNumber,sessionId=null)=>({eventId,projectId:'legacy-project',...(sessionId?{sessionId}:{}),eventType:'checkpoint_arrival',timestamp:'2026-08-17T14:00:00.000Z',metadata:{dayNumber,...(sessionId?{sessionId}:{})},references:{checkpointId:`cp${dayNumber}`,...(sessionId?{sessionId}:{})}}),journal=[makeEvent('legacy-unscoped-event',1),makeEvent('legacy-exact-event',1,'legacy-day-1'),makeEvent('other-day-event',2),makeEvent('other-session-event',1,'other-run')];
    await repository.restoreNew({project,journal,media:[makeMedia('legacy-unscoped',1),makeMedia('legacy-exact',1,'legacy-day-1'),makeMedia('other-day',2),makeMedia('other-session',1,'other-run')]});
    const service=exports.createPhotoExportService({repository:infra.createMissionMediaRepository({database,createId:()=>'',clock:{iso:()=>''}})}),archive=await service.dayBackup('legacy-project',1,{project,journal,session:legacySession,buildIdentity:{applicationVersion:'test',buildId:'legacy-idb',serviceWorkerCacheId:'legacy-cache'},exportedAt:new Date('2026-08-26T12:00:00.000Z')}),payload=await restore.readStoredDayPackage(archive.blob),bytes=await Promise.all(payload.media.map(item=>item.blob.text()));database.close();
    return {manifest:archive.manifest,mediaIds:payload.media.map(item=>item.mediaId).sort(),journalIds:payload.journal.map(item=>item.eventId).sort(),bytes:bytes.sort()};
  },{project,legacySession});
  expect(result.manifest).toMatchObject({sessionId:'legacy-day-1',mediaCount:2,journalEventCount:2});
  expect(result.mediaIds).toEqual(['legacy-exact','legacy-unscoped']);
  expect(result.journalIds).toEqual(['legacy-exact-event','legacy-unscoped-event']);
  expect(result.bytes).toEqual(['legacy-exact','legacy-unscoped']);
});

test('real IndexedDB automatic snapshot and generation include legacy unscoped descriptors and bytes',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='Android landscape');
  await page.goto('/');
  const result=await page.evaluate(async({project,legacySession})=>{
    const infra=await import('/src/infrastructure/indexeddb/index.js'),automatic=await import('/src/application/automatic-backup-service.js'),database=await infra.openIndexedDbV2({indexedDB,featureFlags:{isEnabled:()=>true},databaseName:`legacy-automatic-${Date.now()}-${Math.random()}`}),repository=infra.createJourneyRestoreRepository({database});
    const makeMedia=(mediaId,dayNumber,sessionId=null)=>({mediaId,projectId:'legacy-project',...(sessionId?{sessionId}:{}),checkpointId:`cp${dayNumber}`,journalEventId:`event-${mediaId}`,role:'original',cameraRole:'rear',name:`${mediaId}.jpg`,mimeType:'image/jpeg',metadata:{dayNumber,...(sessionId?{sessionId}:{})},blob:new Blob([mediaId],{type:'image/jpeg'})}),makeEvent=(eventId,dayNumber,sessionId=null)=>({eventId,projectId:'legacy-project',...(sessionId?{sessionId}:{}),eventType:'checkpoint_arrival',timestamp:'2026-08-17T14:00:00.000Z',metadata:{dayNumber,...(sessionId?{sessionId}:{})},references:{checkpointId:`cp${dayNumber}`,...(sessionId?{sessionId}:{})}}),journal=[makeEvent('legacy-unscoped-event',1),makeEvent('legacy-exact-event',1,'legacy-day-1'),makeEvent('other-day-event',2),makeEvent('other-session-event',1,'other-run')];
    await repository.restoreNew({project,journal,media:[makeMedia('legacy-unscoped',1),makeMedia('legacy-exact',1,'legacy-day-1'),makeMedia('other-day',2),makeMedia('other-session',1,'other-run')]});
    const mediaRepository=infra.createMissionMediaRepository({database,createId:()=>'',clock:{iso:()=>''}}),snapshots=infra.createRecoverySnapshotRepository({database}),generations=[];
    const external={inspect:async()=>({status:'ready'}),async writeVerifiedGeneration(input){const opened=[];for(const reference of input.media)opened.push({mediaId:reference.mediaId,bytes:await (await input.openMedia(reference)).text()});generations.push({mediaIds:input.media.map(item=>item.mediaId).sort(),journalIds:input.manifest.journal.map(item=>item.eventId).sort(),opened:opened.sort((a,b)=>a.mediaId.localeCompare(b.mediaId))});return {status:'ready',filename:`${input.sessionDirectoryName}/${input.generationFilename}`,size:opened.reduce((sum,item)=>sum+item.bytes.length,0),verified:true,manifest:input.manifest};}},ids=['snapshot-id','generation-id'],service=automatic.createAutomaticBackupService({snapshotRepository:snapshots,mediaRepository,externalBackup:external,clock:{now:()=>Date.parse('2026-08-26T12:00:00.000Z'),iso:()=> '2026-08-26T12:00:00.000Z'},createId:()=>ids.shift()||crypto.randomUUID(),setIntervalFn:()=>1,clearIntervalFn:()=>{}}),run=await service.run({projectId:'legacy-project',dayNumber:1,session:legacySession,project,journal,settings:{}},{trigger:automatic.AUTOMATIC_BACKUP_TRIGGER.MANUAL}),snapshot=await snapshots.latest('legacy-day-1');database.close();
    return {status:run.status,externalStatus:run.external.status,snapshotMediaIds:snapshot.recovery.mediaReferences.map(item=>item.mediaId).sort(),snapshotJournalIds:snapshot.recovery.journal.map(item=>item.eventId).sort(),generation:generations[0]};
  },{project,legacySession});
  expect(result).toMatchObject({status:'recovery-verified',externalStatus:'ready'});
  expect(result.snapshotMediaIds).toEqual(['legacy-exact','legacy-unscoped']);
  expect(result.snapshotJournalIds).toEqual(['legacy-exact-event','legacy-unscoped-event']);
  expect(result.generation.mediaIds).toEqual(['legacy-exact','legacy-unscoped']);
  expect(result.generation.journalIds).toEqual(['legacy-exact-event','legacy-unscoped-event']);
  expect(result.generation.opened).toEqual([{mediaId:'legacy-exact',bytes:'legacy-exact'},{mediaId:'legacy-unscoped',bytes:'legacy-unscoped'}]);
});

test('real IndexedDB deliberate-session manual and automatic backups reject a mixed wrong-day media set',async({page},testInfo)=>{
  test.skip(testInfo.project.name!=='Android landscape');
  await page.goto('/');
  const result=await page.evaluate(async()=>{
    const infra=await import('/src/infrastructure/indexeddb/index.js'),exports=await import('/src/application/photo-export-service.js'),automatic=await import('/src/application/automatic-backup-service.js'),session={schemaVersion:2,sessionId:'deliberate-run',projectId:'project',rallyId:'rally',dayId:'rally-day-1',dayNumber:1,calendarDate:'2026-08-26',runNumber:1,status:'active',startedAt:'2026-08-26T13:00:00.000Z',checkpointStates:{cp1:{status:'arrived',scoreAwarded:0}},pendingEvidence:{schemaVersion:1,entries:[]},legacy:false,origin:'deliberate-start'},project={projectId:'project',id:'project',name:'Field Rally',features:[{id:'cp1',type:'checkpoint',day:1,name:'1.1',status:'arrived'}],rallyExecution:{schemaVersion:2,activeSessionId:'deliberate-run',sessions:{'deliberate-run':session},daySessions:{1:['deliberate-run']},days:{1:{dayNumber:1,sessionId:'deliberate-run',status:'active'}}}},database=await infra.openIndexedDbV2({indexedDB,featureFlags:{isEnabled:()=>true},databaseName:`mixed-session-backup-${Date.now()}-${Math.random()}`}),restoreRepository=infra.createJourneyRestoreRepository({database}),makeMedia=(mediaId,dayNumber)=>({mediaId,projectId:'project',sessionId:'deliberate-run',checkpointId:'cp1',journalEventId:`event-${mediaId}`,role:'original',cameraRole:'rear',name:`${mediaId}.jpg`,mimeType:'image/jpeg',size:mediaId.length,metadata:{dayNumber,sessionId:'deliberate-run'},blob:new Blob([mediaId],{type:'image/jpeg'})}),media=[makeMedia('valid-1',1),makeMedia('valid-2',1),makeMedia('wrong-day',2)],journal=[{eventId:'arrival',projectId:'project',sessionId:'deliberate-run',eventType:'checkpoint_arrival',timestamp:'2026-08-26T14:00:00.000Z',metadata:{dayNumber:1,sessionId:'deliberate-run'}}];
    await restoreRepository.restoreNew({project,journal,media});
    const mediaRepository=infra.createMissionMediaRepository({database,createId:()=>'',clock:{iso:()=>''}}),photoExports=exports.createPhotoExportService({repository:mediaRepository}),options={project,journal,session,buildIdentity:{applicationVersion:'test',buildId:'mixed-idb',serviceWorkerCacheId:'mixed-cache'},exportedAt:new Date('2026-08-26T15:00:00.000Z')},attempt=async operation=>{try{await operation();return {resolved:true};}catch(error){return {resolved:false,code:error.code||null,message:error.message,mismatchCount:error.mismatchCount||0,mediaIds:error.mediaIds||[]};}},manualBackup=await attempt(()=>photoExports.dayBackup('project',1,options)),manualPhotos=await attempt(()=>photoExports.day('project',1,options)),snapshots=infra.createRecoverySnapshotRepository({database});let externalWrites=0;const external={inspect:async()=>({status:'ready'}),async writeVerifiedGeneration(){externalWrites+=1;throw new Error('must not write');}},service=automatic.createAutomaticBackupService({snapshotRepository:snapshots,mediaRepository,externalBackup:external,clock:{now:()=>Date.parse('2026-08-26T15:00:00.000Z'),iso:()=> '2026-08-26T15:00:00.000Z'},createId:()=>crypto.randomUUID(),setIntervalFn:()=>1,clearIntervalFn:()=>{}}),automaticResult=await service.run({projectId:'project',dayNumber:1,session,project,journal,settings:{}},{trigger:automatic.AUTOMATIC_BACKUP_TRIGGER.MANUAL}),snapshot=await snapshots.latest('deliberate-run');database.close();
    return {manualBackup,manualPhotos,automaticResult,externalWrites,snapshotExists:Boolean(snapshot)};
  });
  for(const attempt of [result.manualBackup,result.manualPhotos])expect(attempt).toMatchObject({resolved:false,code:'DAY_BACKUP_MEDIA_MISMATCH',mismatchCount:1,mediaIds:['wrong-day']});
  expect(result.automaticResult.status).toBe('failed');expect(result.automaticResult.error).toMatch(/exact-session media descriptor/i);expect(result.externalWrites).toBe(0);expect(result.snapshotExists).toBeFalsy();
});
